### PR TITLE
Return an error if we can't connect and limit the number of retries

### LINKED ISSUE #390: Connect without address hint doesn't return
The JSON-RPC call to `connect` without an address hint may fail because we don't know an address, but it currently does not return a JSON-RPC error, it just hangs there.

### LINKED ISSUE #405: RPC commands may hang indefinitely on failures
The `connect` RPC call may hang for in some cases. One example is when a funding flow was interrupted and `connect` is used to reconnect to that peer, but the peer doesn't conform lightningnetwork/lnd#457, the connection eventually gets killed but `connect` doesn't return.

### LINKED ISSUE #681: `connect` stuck eternally when trying to connect to an already connected node
`connect` gets stuck forever when      
1) I try to connect to a node which has already been `connect` ed 
or
2) Wrong port is specified.

### PR DESCRIPTION
**Pull request by cdecker**
Retrying to connect in eternity seems a bit unintuitive, so we limit to 10 attempts and keep track of when we started connecting. We could pass these parameters from `lightningd` in the future, but this is the simplest solution for now. Also this fixes the hanging when we do not know an address and don't provide a hint.

Fixes #681 
Fixes #405 
Fixes #390

### CODE REVIEW

File: gossipd/gossip.c [hunk 1]
```diff
@@ -100,6 +100,15 @@ struct reaching {
 
 	/* Did we succeed? */
 	bool succeeded;
+
+	/* How many times have we attempted to connect? */
+	u32 attempts;
+
+	/* How many timest to attempt */
```
Comment (ZmnSCPxj) [inline gossipd/gossip.c]: Nit: comment misspelling "timest"

File: gossipd/gossip_wire.csv [hunk 2]
```diff
@@ -43,6 +43,13 @@ gossip_peer_connected,,lfeatures,lflen*u8
 gossip_peer_already_connected,3015
 gossip_peer_already_connected,,id,struct pubkey
 
+# gossipd -> master: attempted to connect, unsuccessful, gave up
+gossip_peer_connection_failed,3020
```
Comment (ZmnSCPxj) [inline gossipd/gossip_wire.csv]: We need some good way to allocate message numbers, now I need to bump the message number in #638 again...
