### PR TITLE
Make lightning-dir absolute

### LINKED ISSUE #3136: Startup fails when specifying a relative `--lightning-dir`
We don't create a database in this case. Bisected it at https://github.com/ElementsProject/lightning/commit/e2f7c86271600998f5ae8dca29def108cf834ed5.

```
./lightningd/lightningd --lightning-dir test_dir --testnet 
2019-10-05T17:05:30.195Z UNUSUAL lightningd(25826): Creating configuration directory test_dir
failed to open database test_dir/lightningd.sqlite3: unable to open database file
```

```
./lightningd/lightningd --lightning-dir $PWD/test_dir --testnet 
2019-10-05T17:05:51.221Z INFO lightningd(25837): Creating database
2019-10-05T17:05:51.253Z UNUSUAL lightning_hsmd(25848): HSM: created new hsm_secret file
2019-10-05T17:05:51.283Z INFO lightning_gossipd(25850): We seem to be missing gossip messages
2019-10-05T17:05:51.297Z INFO lightningd(25837): --------------------------------------------------
2019-10-05T17:05:51.297Z INFO lightningd(25837): Server started with public key
```

### PR DESCRIPTION
**Pull request by darosior**
This fixes #3136 and also makes it easier for plugins (to which we pass `ld->config_dir`).

### CODE REVIEW

File: lightningd/options.c [hunk 1]
```diff
@@ -860,6 +860,9 @@ static void handle_minimal_config_opts(struct lightningd *ld,
 			       &ld->config_dir,
 			       "Set working directory. All other files are relative to this");
 
+	if (!path_is_abs(ld->config_dir))
+		ld->config_dir = path_join(ld, path_cwd(tmpctx), ld->config_dir);
```
Comment (rustyrussell) [inline lightningd/options.c]: Actually, path_join() does the Right Thing if the path is already absolute, so no need for if() here.

Comment (darosior) [reply lightningd/options.c]: Thanks

**Comment by darosior** [comment]
> is it possible to write a test case for this? we've had a couple of config-dir problems over the last few weeks, it'd be nice to start getting some coverage for these.

File: lightningd/options.c [hunk 2]
```diff
@@ -860,6 +860,8 @@ static void handle_minimal_config_opts(struct lightningd *ld,
 			       &ld->config_dir,
 			       "Set working directory. All other files are relative to this");
 
+	ld->config_dir = path_join(ld, path_cwd(tmpctx), ld->config_dir);
```
Comment (rustyrussell) [inline lightningd/options.c]: This leaks the old value, but the fix is simple:

`ld->config_dir = path_join(ld, path_cwd(tmpctx), take(ld->config_dir));`

FYI:
E            - Node /tmp/ltests-2io5d811/test_closing_while_disconnected_1/lightning-1/ has memory leaks: [
E               {
E                   "backtrace": [
E                       "ccan/ccan/tal/tal.c:437 (tal_alloc_)",
E                       "ccan/ccan/tal/tal.c:466 (tal_alloc_arr_)",
E                       "ccan/ccan/tal/tal.c:794 (tal_dup_)",
E                       "ccan/ccan/tal/str/str.c:18 (tal_strdup_)",
E                       "common/configdir.c:11 (opt_set_talstr)",
E                       "ccan/ccan/opt/parse.c:121 (parse_one)",
E                       "ccan/ccan/opt/opt.c:230 (early_parse)",
E                       "ccan/ccan/opt/opt.c:247 (opt_early_parse_incomplete)",
E                       "lightningd/options.c:841 (handle_minimal_config_opts)",
E                       "lightningd/options.c:1097 (handle_early_opts)",
E                       "lightningd/lightningd.c:681 (main)"
E                   ],
E                   "label": "common/configdir.c:11:char[]",
E                   "parents": [],
E                   "value": "0x224e5a8"

Comment (darosior) [reply lightningd/options.c]: Thanks, I just removed the condition and didn't check before push.. :/

**Comment by darosior** [comment]
Corrected... And that time I ran the test !
