### PR TITLE
Plugins: don't leave zombies

### LINKED ISSUE #4381: Zombies of offers and fetchinvoice
### Issue and Steps to Reproduce

`v0.9.3rc2-17-g6bed85b`

I see zombies. `lightningd` running for mainnet, testnet and signet:

```
$ ps ax | grep Z
2668521 ?        Z      0:00 [fetchinvoice] <defunct>
2668524 ?        Z      0:00 [fetchinvoice] <defunct>
2668527 ?        Z      0:00 [fetchinvoice] <defunct>
2668531 ?        Z      0:00 [offers] <defunct>
2668532 ?        Z      0:00 [offers] <defunct>
2668533 ?        Z      0:00 [offers] <defunct>
```

### `getinfo` output

Not relevant. @rustyrussell said yesterday at the meeting that he knows exactly what it is. Just noting it here.

### PR DESCRIPTION
**Pull request by rustyrussell**
@jsarenik commented that he saw zombie plugins, and I reproduced that here.  This handles SIGCHLD in a way which tries not to interfere with the synchronous handling of waitpid() in the subd code.

Fixes #4381

Changelog-None

### CODE REVIEW

File: lightningd/lightningd.c [hunk 1]
```diff
@@ -700,22 +700,79 @@ static void on_sigterm(int _ UNUSED)
...
+	/*~ UNIX signals are async, which is usually terrible.  The usual
+	 * trick, which we use here, it to write a byte to a pipe, and
+	 * then handle it in the main event loop.
+	 *
+	 * This can fail if we get flooded by signals but that's OK;
+	 * we made it non-blocking, and the reader will loop until
+	 * there are no more children.  But glibc's overzealous use of
+	 * __attribute__((warn_unused_result)) means we have to
+	 * "catch" the return value. */
+        if (write(sigchld_wfd, "", 1));
```
Comment (cdecker) [inline lightningd/lightningd.c:717]: `clang` complains that this is an empty `if`-statement. Likely just needs to be marked somehow.

File: lightningd/plugin.c [hunk 2]
```diff
@@ -630,7 +648,8 @@ static struct io_plan *plugin_write_json(struct io_conn *conn,
 /* This catches the case where their stdout closes (usually they're dead). */
 static void plugin_conn_finish(struct io_conn *conn, struct plugin *plugin)
 {
-	plugin_kill(plugin, "Plugin exited before completing handshake.");
+	const char *msg = tal_fmt(tmpctx, "died %s", state_desc(plugin));
```
Comment (cdecker) [inline lightningd/plugin.c:651]: Very much prefer the `exited` verbiage, since users usually get confused by terms like crash or dying, since they assume it's a fault.

**Review by cdecker — DISMISSED** [review]

**Comment by rustyrussell** [comment]
OK, changed wording and hopefully make clang happier.

I also added better logging in general (logging at debug for normal expected plugin terminations).

**Comment by cdecker** [comment]
Not up to date with signals, but somehow the signal handler is getting unexpected signals:

```
2021-02-11T06:34:59.1053093Z lightningd: FATAL SIGNAL 6 (version ea82286-modded)
2021-02-11T06:34:59.1053713Z 0x558a1a626f9b send_backtrace
2021-02-11T06:34:59.1054185Z 	common/daemon.c:39
2021-02-11T06:34:59.1054653Z 0x558a1a627045 crashdump
2021-02-11T06:34:59.1055099Z 	common/daemon.c:52
2021-02-11T06:34:59.1055531Z 0x7f38d71be20f ???
2021-02-11T06:34:59.1055894Z 	???:0
2021-02-11T06:34:59.1056249Z 0x7f38d71be18b ???
2021-02-11T06:34:59.1056620Z 	???:0
2021-02-11T06:34:59.1056969Z 0x7f38d719d858 ???
2021-02-11T06:34:59.1057336Z 	???:0
2021-02-11T06:34:59.1057681Z 0x7f38d719d728 ???
2021-02-11T06:34:59.1058030Z 	???:0
2021-02-11T06:34:59.1058401Z 0x7f38d71aef35 ???
2021-02-11T06:34:59.1058764Z 	???:0
2021-02-11T06:34:59.1059170Z 0x558a1a5cbe24 on_sigchild
2021-02-11T06:34:59.1059685Z 	lightningd/lightningd.c:718
2021-02-11T06:34:59.1060177Z 0x7f38d71be20f ???
2021-02-11T06:34:59.1060532Z 	???:0
2021-02-11T06:34:59.1060952Z 0x558a1a690a23 set_destroying_bit
2021-02-11T06:34:59.1061448Z 	ccan/ccan/tal/tal.c:103
2021-02-11T06:34:59.1061887Z 0x558a1a6912d8 del_tree
2021-02-11T06:34:59.1062336Z 	ccan/ccan/tal/tal.c:399
2021-02-11T06:34:59.1063039Z 0x558a1a691342 del_tree
2021-02-11T06:34:59.1063483Z 	ccan/ccan/tal/tal.c:412
2021-02-11T06:34:59.1064004Z 0x558a1a691342 del_tree
2021-02-11T06:34:59.1064438Z 	ccan/ccan/tal/tal.c:412
2021-02-11T06:34:59.1064895Z 0x558a1a691342 del_tree
2021-02-11T06:34:59.1065324Z 	ccan/ccan/tal/tal.c:412
2021-02-11T06:34:59.1065770Z 0x558a1a69168c tal_free
2021-02-11T06:34:59.1066198Z 	ccan/ccan/tal/tal.c:486
2021-02-11T06:34:59.1066633Z 0x558a1a5cc864 main
2021-02-11T06:34:59.1067116Z 	lightningd/lightningd.c:1125
2021-02-11T06:34:59.1067588Z 0x7f38d719f0b2 ???
2021-02-11T06:34:59.1067966Z 	???:0
2021-02-11T06:34:59.1068362Z 0x558a1a5af2ed ???
2021-02-11T06:34:59.1068750Z 	???:0
2021-02-11T06:34:59.1069168Z 0xffffffffffffffff ???
2021-02-11T06:34:59.1069593Z 	???:0
```

**Comment by rustyrussell** [comment]
> Not up to date with signals, but somehow the signal handler is getting unexpected signals:
> 
> ```
> 2021-02-11T06:34:59.1051991Z lightningd: lightningd/lightningd.c:718: on_sigchild: Assertion `errno == EAGAIN || errno == EWOULDBLOCK' failed.

Ah!  Yes, it was getting EPIPE, since we closed the other end of the pipe when we freed ld.  Fix is simple, to deactivate signal handler before that.  See fixup.

**Comment by jsarenik** [comment]
tACK 7ebef8f57c7fd425a11aa281e54ca4cfc75c094a (which is a no-op rebase of 5dd30b45f755d352e364c98733f63822b8704d36 to current master dc38e65ed3def291688fa434233a3184ac7fd9a3)

Everything works as expected. Thank you @rustyrussell !

**Comment by cdecker** [comment]
Rebased and squashed

ACK https://github.com/ElementsProject/lightning/pull/4382/commits/53d7188c79b18838e245354846e9a9240ad03b56

**Comment by jsarenik** [comment]
ACK 53d7188c79b18838e245354846e9a9240ad03b56
