### PR TITLE
Some more minor patches and fixes 

### LINKED ISSUE #233: Add some slack to the timeouts in order to avoid failure due to block while forwarding
There is an edge case when doing a sendpay. When a block comes in after the sending node calculates the locktime but before the receiving node does, then it triggers an error as there is no leeway at all in the locktime checks.

This in and of itself wouldnt be fatal as you could just do another sendpay, however the problem is that once a sendpay fails in this way, it seems to get stuck with a "still in progress" result after reestablishing the channel.

Of course, there is nothing progressing anymore, so the still in progress state is permanent. The only workaround I have found so far is to clear out the sql DB.

I think if a sendpay is not complete and there is no way to complete it, it should just be closed out (however that is best done) so another sendpay can be processed.

### PR DESCRIPTION
**Pull request by cdecker**
Minor cleanups and fixes that came up while trying to integrate with `lnd`. In particular 7193e0a510bf6e4e7ecf58bc353f7a2fa8a93627 uses `min_cltv_expiry` instead of the deadling for announcements which is the correct value, and 440b0a03456af11bcc9f60fa622020295130b67f "downgrades" the sphinx packets to version 0x00.

Closes #233

### CODE REVIEW

File: common/sphinx.c [hunk 1]
```diff
@@ -357,7 +357,7 @@ struct onionpacket *create_onionpacket(
 
 	if (!params)
 		return NULL;
-	packet->version = 1;
+	packet->version = 0;
 	memset(nexthmac, 0, SECURITY_PARAMETER);
```
Comment (rustyrussell) [inline common/sphinx.c]: This is why we quote the spec, and why check-source checks it... would be nice to add some of that here!
