### PR TITLE
peer_control: send addrhints in activate_peer

### LINKED ISSUE #527: Reconnecting when app crash
Hi! I'm running a node in testnet, and found that when the daemon crashes, the channels stays disconnected until I force a reconnection with the cli connect 

Is there a way to reconnect them automatically?

Thanks!

### PR DESCRIPTION
**Pull request by jb55**
Since we now have addresses in the database, we can resend them as hints to gossipd on startup.

Fixes #527

### CODE REVIEW

File: lightningd/peer_control.c [hunk 1]
```diff
@@ -2734,8 +2734,15 @@ const char *peer_state_name(enum peer_state state)
...
 static void activate_peer(struct peer *peer)
 {
+	u8 *msg;
+
 	assert(!peer->owner);
 
+	/* Pass gossipd any addrhints we currently have */
+	msg = towire_gossipctl_peer_addrhint(peer, &peer->id, &peer->addr);
+	subd_send_msg(peer->ld->gossip, msg);
+	tal_free(msg);
```
Comment (rustyrussell) [inline lightningd/peer_control.c]: This works, but subd_send_msg() supports take, so you can simply tell it `subd_send_msg(peer->ld->gossip, take(msg));` and it will take ownership.  You can see that we did that below, for example.

**Comment by jb55** [comment]
> This works, but subd_send_msg() supports take, so you can simply tell
> it `subd_send_msg(peer->ld->gossip, take(msg));` and it will take
> ownership. You can see that we did that below, for example.

That function scared me but I will switch it over

**Comment by jb55** [comment]
Pushed a new version, let me know if that looks right
