### PR TITLE
Track coinbases in wallet

### LINKED ISSUE #5564: fundchannel(and other functions?) spend immature coinbase outputs
Mined directly into my wallet on regtest. Seems like something that should be avoided if possible just as an annoyance.

```
{
   "code": 303,
   "message": "Error broadcasting funding tx: error code: -26\\\\nerror message:\\\\nbad-txns-premature-spend-of-coinbase, tried to spend coinbase at depth 18. Unsent tx discarded 02000000000101e2cda28e18c7f3aed67ad1f602af3d05b3e8defeda960072f0128db1174b1c280000000000fdffffff02a08601000000000022002047d39ed3ae6ebcec8f34be245ba579605d2073bbdbde27cfddbe2cdd2b1cfea1c66a042a0100000016001411a9312852c59f4ffa4678dea7448f6ade462e9e0246304302200f27ca1bab7bc9878a1f48e1731c57eb6ade326c30240facf39ec943c9d697ce021f35ac0cb95bb4b1794307c85a9153f8c561a1fccdc3b196ee08aa66f5af4067012102f8fdb6ded596fb1b73059eceda5f59f28739479419adfdfa7dec6d39a2bd2e9e66000000.",
   "data": {
      "id": "036a76e9bebfc101e93c6034150759844a0d10cc0012f4fdba19bfd3b94f963b10",
      "method": "openchannel_signed"
   }
}
```

### LINKED ISSUE #5696: Channel stuck in CHANNELD_AWAITING_LOCKIN after Fundchannel all
### Issue

After trying `fundchannel id=02c6...ee5 amount=all feerate=normal` on regtest my nodes ended up with two channels one in CHANNELD_AWAITING_LOCKIN and second in CHANNELD_NORMAL state.

The only nuance is that i funded channel it in 2 tries: 1) funchannel supposedly failed with immature UTXOs, 2) after -generateblocks fundchannel finished.

So, i guess this is somehow intersects with other issues like this

https://github.com/ElementsProject/lightning/issues/5564 and this https://github.com/ElementsProject/lightning/issues/4791.

### Full log output

```
clg-reg fundchannel id=02c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee5 amount=all feerate=normal

clg-reg fundchannel id=02c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee5 amount=all feerate=normal

{
   "tx": "02000000000165f3b2fd464ba06eee0025c39d3ae08b48323ec83c58c7fe8093fb97eae0737a8e0000000000fdffffffacc43712f4b77d91730fb3f4230814fbf4fa2d7e0bdc1b1d142b4285c55ff2490000000000fdffffff6329f73b8b719bf7bf54b80f6378d5613c466b39627e30d00a5708d8df6380a20000000000fdffffffc98a02dcef6e5c27d43e7fbfac6a72849a817c1300f431d5512fdfa3c65228f50000000000fdffffff93ef4b59d346f48ad19bc1606e92947e608a228c082cac2730786f67254309310000000000fdffffff9cc664dd34f9b6c018372a403c1a0f097377265c7dd9c2ce1dbedbe023a3d27a0000000000fdffffff3b7cdbdba2b23b8341b440cb6c83d1361cbc008ecb2e4f0ae1b40c882745f3290000000000fdfffffffc421d04bf990de3f27a4891a5a7a632b7fec5a35da088f37f788891b18fcec50000000000fdffffffa475be3d811960bd3c76a376ded235af8da54c8f7dd246e7e85fb4f5ad0b34e40000000000fdffffff37f6212a405aec3a08214a86604f6e5e221a90233040f0b4d039ffa8ecc4acc40000000000fdffffff43c52f0882bd1e2910e2047cc7353992fdf9170345bbbea70d8c22a21f7618580000000000fdffffff843e7b301b0ce5fb9d4ae2771491305dda614f3a4d309aed9a6ec6a3731642520000000000fdffffffce03e820606e698adb84de894f72ad0d30cd63dc93e8f76bb7aa64f149a7e1000000000000fdffffff4800af8a4363a049435194c42a0e0cf29fd2b57ec974cfb2ef1b424381ae4bb80000000000fdffffffb21f43c600d3f5612f657777b4c87655c311874a024a7a2d5777595861ced4740000000000fdffffff87a73874247d33d1c736c2278c40999a422794a8619422e4f114c1e18a702b7a0000000000fdfffffff455ed4cbb44c52d0ab98d08dd87486ade1f90f151acddfc4a34a6fa8f27ed420000000000fdffffffbcbdcb342636f5a9cff950f5d05b8c0e4e1d1d1a6945e27616ddf6e2bb4afeda0000000000fdffffff3ade78659a07976d825ab5856d4106e59c2a262731b30ba50932463b65792ca30000000000fdffffff87e4f724b1019067ed9923eb212b91c74e62d6b21ad55ea09719f84396a79ce20000000000fdffffffccabf03cd198729d0ce1650135897acd57b6caf0e616c2ca3fd13e93182e39280000000000fdffffffc0acd7949c09c449bf4e727e54cc68b5f5337cb485526d4b4f664b86fa6da1550000000000fdffffffbd39e287afc749a1e0923e94d594bc72bedb0f3eea8e1b36a9f594bca0c51c150000000000fdffffff7f03765eb0e1fe23fd1bf375d1e76106afdd964195946329d24e1f282188d1e10000000000fdffffff4b452e306d351b10dd589b47b7c825d95d5d182d9486aa08ab0e26af3ab437d30000000000fdffffffab17430e561ed6ab9203f2a9b0de634d719a2d3cfc71bfd1e46b21b7203889a00000000000fdffffffe29ab116f56924a722490f8b83f14194bddd88d09bbdc331e3441f837bf402b00000000000fdffffff09af5cebb132f000d094b1200f6ee6c9b2bfad9618ef3b95de4eeac57fdb1e8f0000000000fdffffffdf6c922f16fafa0d1c5cc400d995f73bf05f3cf2b1e5306a2b4a8243fa5159820000000000fdffffff581ac6df04e5d180d00c393e92d9d69b8478cc16118be9b1bc95580ac09a76ff0000000000fdffffff42b98d906481f75c9308369ce9dfcd6c1a6d10f22c7ea2b3090711fa9367b45b0000000000fdffffffc659bc6d7de772a2877b14271e92e1f2cb802c1f52fb78a0f7365e7382797f240000000000fdffffffd5fb0790581af60df866e4de153819ba88be7d2479c09b29c186026c6f255caf0000000000fdffffff18c286a59fd9e01c3e650a107f30b173473699f251119fc03f49425318170c090000000000fdffffff240a12d103edae851eaa7aeed1227cbdb1deeedd5e746ae06c76d4afb887f22c0000000000fdffffffe30718c676f8332da9e95ce50ec577b799fef15768fe36fea66dd66feaaeca040000000000fdffffff94b02ccacee98f06326283284c5823a5cc7e47685ad8053bad32f2ea25a6d26a0000000000fdffffff2ad153cb3d545d805f6affb6f8c8dd162a4b7384e2423e6537638b63b966708a0000000000fdffffff5be2fe4b4ae623d2fb60864880663be0c0481f6c7e4b57d9e18a176417c7670b0000000000fdffffff850823fb717b5b34006438fdf35046a8a0773fd9ac90a38b76f4297d7af0b6630000000000fdffffffa3d56dc74715135f601ea2e07f49baef2a5bd3c2da362b95a4e8f794bfd5f8620000000000fdffffffff600783a37c5855a55e19162a6282392ad0e915e3e3b718e5964d6fdf7ce3960000000000fdffffff68b481ac423bfb3adbcc384936d511fe37893b8d02b66eb612b9005d2ffe013c0000000000fdffffffc8d03d0cc0f53a7cd6ba2874ba30bd16f610f8f1086f06ef330da4ead872b57f0000000000fdffffff49ba3f7aa7a7b755f5d3d42da72d968a6ab4dbf49f54cec52bfa42178573a65a0000000000fdffffff20491dae8b9a507687a2fd795df26ce13ba96666418ca938a1bd73ed78122c970000000000fdffffffec4732dc49813b83d0640448e84e8c8f66e3328fbd3a86ee72694fb5870434930000000000fdffffff923d212b1e2e184c5dbdfca08aabdc2bdeff842ffa9bf25aff121efd368a1a430000000000fdffffffe204fba903c29ad9b3535d84ed31f81f2f4e3ca84534502290cbeb34e81262170000000000fdffffffece66608840017763e4efe66872c02ee2278427a8a088e66a5fcbc5c7b25fade0000000000fdffffff307d618526af9b61205e31771e3e9b72a6ccb70bee65a4dbbe772bbd67c17cfa0000000000fdffffffac626cbb320231555c8f64c1594f71ccd618774e71a15292cdf889647ef3a6d50000000000fdffffff090bc90becacc701723867d2da73a2118c267189151c03c9b8901164912e6b470000000000fdffffff4c046cbf97eb4b67d6c3a530fb839d77ca6f5617e23b0798f06e6de20bcf32d30000000000fdffffff5e4f344f9b464f1569ac4373559e163e41269366fa91f84470184c9717837e890000000000fdffffff81d9a88774641946c5e1caa7a4a959e9d36f052820754844613d3de574b9af120000000000fdffffff54e724a143254f50df518ea197de712c5d1721d7e1362e49dcd1074e4ed007cf0000000000fdffffff00c66be2af86dcbddcef690fc565513f5d567ca4b72ec0c8484a049e691df1e30000000000fdffffffbd02c02dbc62b84459f742b863c46350dd73c30a7aafaf8451553956810daac20000000000fdffffff60ca3cb26bcdce5efd0337fc1caadac5e6fca7a5de7804ab0603ecb39eed0a330000000000fdffffffaa59bd16aedcd3e0ca0206cd3db93f326140473a8a3de00619d8632ec1b587da0000000000fdfffffff548d8374db2355e35a70d5072f8e6567c7d223be5cb7f5ab09409711a65e8e50000000000fdfffffffb5d91a61c6e60ae1e430a131b8671f882c12baab84edf055db8feb01839d8600000000000fdffffffb47d3dcd8596f03332eeee2b4a89076c4ad927194ad35d660c4725ebb2a9ae140000000000fdffffff27d171a61e02bf4457a6773dfa516d03f5c533ab50064620479125d76d358c5b0000000000fdffffffef903a926c55f7e0f3b1e9b613da1a67b7c0536d5062c18342d670ec8f9759250000000000fdffffff076ee0ff48832290f449b08fc8dd24076312e45e9445cb9e8f42497b4c8cce210000000000fdfffffff0abd0a426b70bc928d299e953c10cd54f131fe0b206e3cc21d2e901a1683d860000000000fdffffff6bab147baaa99eb39cdf14aae145e4e54f99f9a85e3c2e7a45a11d130c99ef580000000000fdffffff648f450071e429224e86bf0163932fda6f1b19d0eeab4ae61683ca30e6fb0f0a0000000000fdffffff79662f6ca11181f36febdc1463b65715733b72bf0758995b40ac4eaa1be2b84f0000000000fdffffffd2a225493ff3ca3214f955d9c35aed2136bb9cf7c7da83cc5bb47f2e31b25c130000000000fdffffff810181330f7f0d4f0c5b0a2c2d3494ca7b8fdea68b63feeed66bfd40de448cba0000000000fdffffff92202d3e9103c35cfc102cde0f726ba75a42677ee73dfd0339ab6117dc592bea0000000000fdffffff8d5636eca5302a50b34f68c420fd84c027496384bb63a1a1ddbfbc6b737729aa0000000000fdfffffffb2a0f6f801e6ab15b94caff2e643bb71ebe4492502cabe194e6015a5f46715a0000000000fdffffff847d2a67c50ed12ff85a2397c8092c272920b2bd397fb994d0692609c20e461c0000000000fdffffff4b3c2304b0e837f675be4fa91b54d5fe7dc124269ce0eee770d6fe53436e6e9f0000000000fdffffffda6b352f38ac4b7d5229145685ceb630d9095516ba147ae2cbceaab9443054ce0000000000fdffffff74eeb7edaa023bbf68a3beb5f5e15f920c856e4ba42bb8bc6ad2d15c53e91f220000000000fdffffff759cee5ad0ab703417b407a7c9a591451a94f696ec12b6303d03b4a70223a0390000000000fdffffff5eba929641615de08c400c280a4f8850dfdb1f9a9cfcaf9f1172acdf3b4d01f00000000000fdffffff2d64bbb29e87e3290bd07bbb04270ad667501de57e6b56f9ccdb3302a9e590d20000000000fdffffffd45a71ed907d6bc80c4ef9879572ed37ef7bad33597e4890df2334ad7c48782b0000000000fdffffff03e70ec474b571bc87c51037ce5808d776d6a479f92f2da3c3053c51d30cb20a0000000000fdffffffae45a1a7a9a7401904a0f4da26e0ea14b5725d2296e2b8e21c7785962ddb835c0000000000fdffffff2b9c8b02f5ddcad45cbbdb79ab6e5be3312c64ca5460395a028cea231ffe006d0000000000fdffffff7d2b58c371e97f96334a2606fcd6c082aa465acbbb12d70fa37f690cd713fc540000000000fdffffff22193016bcbc7f158573d2aded72dccfa786aa23129b386945f356eac86d67d90000000000fdffffff9c991784e8eabb8c96bbeee10e6327884017a7584c8a2d13b8c3394296dc82700000000000fdffffff8d89fe2a557d6f65bf45171c77da0ab7917c917523c539fabf151af01bcec9c80000000000fdffffffdbb1cc2740364b1666f9fd2d38123ba3cb4956b6dd861b397f6c988743db2fc90000000000fdfffffff19035a46384282c95fd65ef3c955b861177be9c23d539e5bd4c5a40d6ca3a180000000000fdffffff267aeceef53d09d92d682fb6b6df049f618712dc160cfd3c9cb068c058fb99ba0000000000fdfffffffa3231de315a12a9c979a61ea0a874e4b49626c150ba706b71568d26fc4adb260000000000fdffffff5053dcdb6684ac784f2eb9f6f3d03965212f2619eb27a5c5676bd5affc92d2e30000000000fdffffff6e23548a39d98adc3b129bb20239acc56f225c7fef703ff2a00ed9ce53909bb20000000000fdffffffd1e583861e033a86b63e3bb824de528c2707492fc0bca998a49b0eeeb0f993d20000000000fdffffffbe1a17e96bb0d5dbf551198223370add71c0e17dad47f5362266b39a556c0b490000000000fdffffff87c8bc661aaa43984432bf72710a66979e8b897470c9113020782cfb935e3bef0000000000fdffffffb9b2034e64b2eb1899139a663abeb98133126815a4d0c522bb1f1182147e71d80000000000fdffffff02ffffff000000000022002062decdd6ce30a66604380a7e684d861ea515b3af5566b9e3cc23c1d2ad72f59d6006bbb9560000001600141b42e1fc7b1cd93a469fa67ed5eabf36ce354dd6024730440220755e7a647996474e7d27693412a947e23d53fca3dc3cba451236268346409c3902206e97927ff239fa1e0460aa024c6144bf7e81877915d1ccc8244f4f575af67dbe012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b0247304402200bed9773867710eb0165dec3027a805613f3bdce68e5db1ef181de6bffbcc35e0220713a1d4e8ee63a6ad40b38374206cf9a94e42932e09701e905cd47110ec6f100012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b0247304402205411945e3a84ebd32305892dc029a16c14f005b59cf55e0ff666df480325b3a602200e1549a93c22991671d35dbf5189838b65665033228461ceb0e09eefc7e750b5012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b024730440220698ea9e688c47ad7733d6522ef917daec8519b46112f709847f871665e32ac63022069874393de0646bc868b38d46f2c06af966c6ab826571a29ad3858ee75384ecf012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b024730440220362587b375b831053a89c3ccf17c669714e1d02340c9204297eb8e3017c4f77802206d642fa36bb1a84a861c6a488e2905e96c99bd6c72b050b002aa6af3d71a808a012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b024730440220388cf65fefe735abc971ce78d2d593b50855aa1421e92742bc8a9125a63af2a60220570d79eae2c0c9907ef1127e580d12b952be1eaa6d826da6f7b349864e3dfb62012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b0247304402207fcaa9ca0dcd1e48b7abe3503d880d22d46f981c2bed50223a74910466ddbebb022033ec1cc294d1e20eb1a9e3260f146e91a172f64061834e0c3d0f8a9bc636102d012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b02473044022053bdeedb3a64f6166c99d31464ea1e585a819bd35e1000840f50595f38b51bc702203409a89088e16789ff35e02a2763d8ef8605b9669c9c9d1e00e70b819ef476bb012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b024730440220679ad7af3009001837d3bfb1f3809b963234d26541fbe5e2b2836e38ce4b81b502203d0f87bdf85ca839c7a007ec0182158c47cdaf15c52ca91e25a8c6ff64a30295012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b02473044022055cb15f57339458c99d6dd9b92cac25330b6bddcae90939c9f3e91b4a971382802200b0155f6acb96457ea9af3416761643c355ca201c135fd5e08189459cebe7132012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b02473044022032b897486c2f3012ebdce13d5528bb9ed8b7c1893327c986820e98415f175aff02202667c520e31c3412a0d14c16045752306035f4517845fbe5d8a6680b6a055490012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b0247304402204021da35ba1bad30d8d3c8afec3a8fc2a49d91f76271f7da1ecbdabdfbc3fcab02206007a493a7189987b08b2fbf7c87d8a43a4a3c8fb89430122645e6adc87b1829012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b02473044022027fee05173f2dd252ee611880135d016a455657f0e5b829b71bf6a04a489b988022074529cacc10eddc57e009ad0adb7fa8537aab7b387c6b61a378ffcd22be99b5d012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b0247304402207fc3efd44995a3113111a36175c41fd1327c3c7a2d734a5f3c5569f3a5e825b3022065957ab574c3ebae3500f501a9af2da3b98991086b81690f35088b9fed2b6637012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b02473044022014ca6fdeb86812771d5284d4a173fe6aba7ec779cfb3b8dc8a905252a05f9a90022078a74d9dcb000cbcbfe71e4d5d6d5abee08a332d9473b07d057b05bbc391d8e4012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b024730440220370ce87a59c001bbd42e1c60824e524eded46a9bfa1687f41b84c21d7303a1af02205ffd54d04c4ddb1f4c651c61c6b1d1114a11d65c5ec6076b9fd4531d72a9551f012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b0247304402205949cf247c86d3fe3f57a4f983374fef846efb37b41afbe80ccb7b385bd8678b02203a6261ac81fa4c2792f029faafa97c489595e9de19500a298b9f20ad5358bb41012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b024730440220589736c8f6e4ac6bc461991cbcac203cb4c58bf475f3b3199af47158e0fe717802200b039d79ba3614f4ee40e2753f2a63698d56fd5e5115c5bd8db3c7e60319eac0012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b0247304402203e74bb5e5fb368cccc7fc348f52acdfd7ae392b897ffb01ca5f9cbf3a63e367802204ae4639f972a4d20cce02926575b6462ed0fa0d82b8e37ffff9057edc4cc2234012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b02473044022067379d179ef4b4ccbcb996b5fa44ac024be135b19f7fca387a7da0708a0216b802203bd68c76802acae6954a741aa63daee39c97e90a91169a4f21c1d2cdce843daa012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b0247304402200c79d34b7a64d927d0d604074a51e349100e877789e352f3c234fc6e09293deb022023ed8fe344895e276bc05d0a4599ee7f96bd7b12205be5575e3beef31278e2ae012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b0247304402205636c8a6f69da38a918079af669ee1f23b33cb27a39a7f69d145e787539a032302202078e4863d8b6c43c23de328552f4cbaf9e99cefc3734f0586a87776c811275f012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b0247304402205114409b901d183d0c3921fe6db960a95591976c5b31a1a7199486b962d13f1d02202346ccc0bbd23ace8c0007ce0348a2a3264fb09935a4899ba402972cdf7ef6d3012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b024730440220348aa6d5c36bac2df9a4001d5c2ef9625579a474ce92210b3b7ae12e11b9fb0802200f1f8105dc7023cfd2cb26a2406cc8c46f66b2903966e69d861183df708b7546012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b0247304402207731ad53eef1e74cf7fa082c9311bfa5df99d0c750fd2f036badd6ba94a899d9022071cd5e6a917164783766a97d07ade840d3f22dc26a2f276e875bcfbba261f260012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b0247304402203ca525a504566f6082caebd0098eebb787d1f245042bfdf769de66f0e86ad5ce0220080acd56ac49e86570ca6f75b8791f915e76f060071d3e0b470cb66dd3a37b9f012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b02473044022019163df4a8698561c0f3ce2bbca85c9b8059c293ba02eff23a391aa05921c4db022009ff581c0748e5a73610d19f56859e464bb57d2cf5010e3df6686bc991104862012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b02473044022040ef9040da9c111998679e4e8238d59bf06a1626dd471fd0112a030b67182fd70220047b3b3c785badd42fe6af3f84fbbf0e6269b3ab7239ffd36ca41bf49f8e6f6c012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b0247304402200a33bd3f6c665dcd5f127427e36ea5402438773fd86f1120bc5dfe1eed3625ae022009871e086e773f981c57cb84fc796cb8789de38a94a6eaf729c04b58452793f3012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b0247304402201da599dcc25f26615ccb8f7587b128f1c73a1bdf40057865d154a0e807cb862202204eef87de54801445d9fc4eb003016116f798bdec758321799e2698882cd35ffb012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b0247304402203fff1f984c3b865c7adbfe1867a93e4c7634e36407059afc51c2f856827e5b20022062203c14e49d3b816233e2716276a38a3efc3ffec12cbf3f8be2b6407baa0394012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b0247304402201ffa2af5cdab117a138fbeefeb2921bdaa7daf098417ae59329fd062ed8eed1f022067d5b7021501f3e497d4b79d8ce689a4cfaa245e0554674c99b19c28cf4ac406012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b024730440220474a45e2c7c99a4726f53f1a62cd33ae8094086ed09114c2cc42072f95990268022050bce56fa1ad8c4db9fa669f236943d686b8d6d848350b661950ad0192b9ade9012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b0247304402207d0db13178a5128490eedcff2bcf9b040c94a6ac16f4c80f4ba597cdf5f0c087022020c039341d5aff0bc33ace32da8e77d12e63d796f1388a39ef823236f47d2a39012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b02473044022050bd41ae1d37b6ca6a0b3440a3b20c2c14a693cf35b313f6219e32f1ef7de2d7022013f0a1b54cee80f948bfa2a4ac18627e4fb01cf67a79e26eaa310f7b32bd0f5a012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b024730440220302921c2328aca09d96b5faaa87dfd1d1d366e505b95b8f9feac7b614dcb81be02204586a926b8f582c9e0f5ba93b691271d135a6d62e34cf5e3c0831ee7b2f010f5012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b02473044022064735aa48319f80e31e86e1e21920ace539cf99932eab51f1c8e0edfdc90f4ca0220307680518153e9403ee26e5806ae425c7aece7a49b85eb1adf3c5f95d9c0f0ff012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b0247304402201b7c3160e80b1a75de2762cf9ef246c8e01ac2fa9e582647873de0ad148f098d022045ba16df390f980bf3a61daa451692459f3f64ca324218454b21cfa517e023f1012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b024730440220549dfdc337d0ac646d31cd81649b5e9488a6e5c273c54785754da84d1a96dc9f0220620af12f072f0ea6c40376841e03ebca2527e01dad1f61f69fe09cfe46935a98012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b0247304402202e7bbfee948392138f079d69e839564694b40c5c7b9f96f8ac07de3908f1370e0220765b5a0d4fcb5a8e57edb9334b897036f1c4ce966cb16a006675ea039313d7ee012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b024730440220303a86d4983f2af2103f10712987d4d783b96155f5d5d6a612b68c4e7a4975d202204d8103e974a0ef4669982fa61e1db0073b219fc1666dae41fe79d8a259116e58012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b02473044022048b809b366886ff434480b7a4cc0e1a40529f772a5251f0139773b32b17a6509022000adc92ce746b649d107696899636be9c875a40722132e42cb14bc2c31dcab71012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b0247304402202c855fba9f7cdd93c07c3109b6dd43365cc2063f98626fb4021a5b71791cee92022040e2e01b12f6888f59b5ace8155d084cff25b460ff862596b1d43330929bd7eb012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b024730440220682dbd9cfb6fd5edb054f7612771332c79715f81ada7ed45d5add819ae92584c02201af45af7724c921b07641484052e3010381c56a6c0e1e666db9043f9ff1e50be012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b02473044022037bdd4ac056c9639c042ebe9fd0d7a688dd6eb9bc0404e58a013fa1f9b44d8c5022047334538a728a3174c5bf61446c5aae93cc3e16d78f066b91b354f01dd0e34aa012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b0247304402202b52fbe4c43448f4d7439f58d7c5435d3519e79128e08215bb4420333f8da22c0220652c2d83153c09374eaa7dd00362fa54fee92494e21d61f66f4cc0705aa8b988012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b0247304402201583a4fa4fb582f5cdbc924687e6f1c056fd2b9d19aea17e0f06fc4b6dc8504e02201c2468aba9d95e495a3004d4f7da8b190a93b9162a19fd2e7c68bcbc7b63e932012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b02473044022061284196f8061f789dc271db42955caa4a84834ed1c2a37681b7a9956354915e0220152dd02ba1f6fcb01cd4b800672587d424c00202b79fa04861a0e5e0abc10dd1012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b02473044022077a73fb9c2b7f63906bd458d454fcd2ca1ab5b2cdb9005258b6bee7773815730022040035a7bab99f351df845a2f7564ae357c34d0348d1321f8b35821bc0465bb34012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b024730440220608eb6195c24964423f6aaf7b1ffabd189a0f809cca4d8fb601b8fa3c14165570220340180d6d92c05788f4ab5ea07ebec3fbd61d4e3c618194345cea2184c142c0d012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b02473044022014f2c53ada12a044ed017f7264c5903131efc5f8b39530fc352a0c20b6cefd1b02204d45ba009c9db4072d04a5c4bdc220961a9517ced9aea869f29892c083e7c36a012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b0247304402206a941b9f6a87eafe2381e58e6e4b88440915b56fe98e76366b791e983d3dce2902205e9b2d95347ecf541914c1913068419f0e0d5929de5cbc9e46d259d36ff48a16012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b0247304402206dc5f9c7f9ea88340ce213db69bbe6f638e35b7f898a025a46e10814b2e7668f02200ca0c3e94fcf70fb7ee62bad97cba2aa3bbd64aab36dfb8e6e667f02dd845f59012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b024730440220451b90468d1a437f8c5e775a7ffdf4ad9da8ea403f6dc9fd0449962c3fa3b271022015b35abba5556edad01738ee2ccb7f32558708c9c5364f7f53d2bce4462a6eb6012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b0247304402202c1d10a50300c0fd4efcf9ee86e9a83d45236b32a160e1d1fed2fb2014ba7743022059597a02d57722afcae646b813143cce665686aba66c7738814bc7d2e8068f0a012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b0247304402201776d359b4e6114b783630953b50704fb091cca2a5dcf945ea1a917df754cbb70220694449baae6761672b1eded4e66a870da41fc4b17fa8b5968aaa2401dfbc49d1012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b0247304402206a518e308b2d7b6fff51d4b4ed63d85144fe291c0c4ac20f3dbbb18bae893f0802200a65d9fa1b8fb3c1286ee2e9ad72a41abe6487911f944fdaa25f6ae7c392722b012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b0247304402205fda9ef52c4f93623d0e08eedc3b9eaab5b43a22bd199e99e012ae0748bde20d022070f878216ac0f5f682d2af0126f5dfaeb3ca4f14660e06dd2830a02c3be1b773012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b0247304402205ca3da6d35484b3bd5990655db8ff2919e6e3076b67ed9047fe72608c9b796e302201f1e0c29d75714e28a22c5e6ae3d91dda9dd7066700808bfcaf9cdd7c2a198de012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b0247304402201f587d63037cf81e357b8d473d70e41636f16728d7304e8794966a96f18ab38a022047418907ace304a53afc5433aa712549549d881f87185c99a6cfd0d1ad8065d7012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b0247304402204045994742f5344c471548270309480f8187a9a5cbe9f1b47f85b9eef250b6c002200b218f7de714bf65a38b4ef91dd82743226260bff9d923680d347c1bd1ff99ad012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b0247304402207d1d45256ae93bc975371bfb92cf13af72528b44be256853bd5bbefafa1ef51d02202197c35706041067fb94729c4349ee5315034c978df580053387f97607e5f08e012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b0247304402207123fcc7022901040969975627ad83fa4b5863ee9c996bccf8fe774c864f2c64022028839e22d318edd4dd5843820909effae723705d3976a2290909beaaf9f7d9cc012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b0247304402201386853b8470fb5cb6fae8df3b238fae63e4286a34faab81665d8b7621256dae0220622aa22684c47099b1e2825aea854dbbc72532e6acb3f20287afa88d6687e5cf012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b024730440220793e01341b2ac72f1fa8fe226b359ef3432478c85aa2896c35e70d59686ac2bb02204847252a5a01b6da51facc66c987f27a5b9970af53efa330e4ea1e00766b3673012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b02473044022017ef9e5b32da49b6681a5080015167232c968e8846058ab4fc3a5a65190559a902206186a71efdd543c39bfe7e8834e8962942eb8a8b3d44d7d1bba37186d8ceea5e012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b02473044022063e3d2612d14f8ec2cb38b79db6e71b50c14fb57c6e71c686f3374e1e97e017a0220507e38d5ec7b0c5fb1953bf11530a178c820a3cf41edb4f2a9307510e148b860012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b024730440220347e20669c593d70dc20f8f264f77dc83040774966fc6e7e88cb312b55225ade022076b68437cf743035fb4471b671e35ca7975e860fa64f48c811af4b3022b4f003012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b024730440220476cdb70756a59e8ebe3df27c4dde36dace7abf071647250ae85385ba8642a2d02205f72a25d3ff6f11a65f204948a1489a2441e239251112ce0c0cc4b29129a4866012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b02473044022049fbe592f10ab4e18df59784f7934c262882ce188059032414e992f016bd9ae602203e06f764a28d3f691976cd3f2adad0546b16d55bf8655705a8b9ddf3b53a872c012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b0247304402207c17b2f38e4067d020ba82de5cdb1d9e558f22506d271c9a17b32fb43b8245b3022037e16f71b42c135e7a86d66b439f1ce68d6dcaa250d5c9a9c1bf25432baca8ea012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b024730440220423aa9e5f5d8948dba06843bf17e76430e34f2b884458662c09d108f601ec6ae02204de6d3cc81e91f328c54572c32c2047d5983c1c009afeefe28d55ab4d9269b5c012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b02473044022014365559a7a4037e402074af21e18c2b1080069e6fbc19fd027d133f504727000220692afb47cffd00a43867369837b703a41f056c276d729d6b5faa316479966d8a012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b0247304402205c75ecdf6f8ce23da27a00c92e21dbdd9445c0c7a658d95aade2737bd24728d2022047932ba7b1d47d4d7f1f5f2cd54ac39094a24fb8aab17af152f73d24c90c9931012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b0247304402202f1342e82d24d0e6836ff801f623444c2dfc80f18a61f3918c35c0e5425f646902206da07c826ca832f9e0d483a56391ff1ef42900eb989ffb530f1296f1097c991b012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b02473044022079dff6cb1afef9a166d035bbbbcb174c5fb3f55b1b20d0e05e859ed1cc9e8f2f02204033e04c8d048f5aab647f479b58f387e7f149c0384bc626226a9ebcb9af472b012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b02473044022035ead5d9ce8ba682ee1bd3cd62bda05fba5cff102d2b1dfc4272953e0c9b72d1022048d2ce5bb32b95ef4b545574a56909e2f1e2f8640981abbc5e40f572092fd649012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b0247304402206a585f324b7c7bbfa168efffe6c85eadcebc90e346f39c66a351acd69ddedf7e022063edb03b731d145969eaeb14b85fc2813dc1e4dbf4385ba283e6f90f6a54e2bc012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b024730440220506a1a3b1813c9420ab89414b4eb67166a97cc7b79ab6d2fc63a7ba2edddfda30220134f6330e6da24a21c58c2fe1309e68254e3b7e963d0a0d29f5c0822b4b371ea012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b02473044022028ac40c21ed83175ae3ffb2dc3c735451bd7fdbc7496a4b34f225efaa4b5e49c0220429d5a30b55b2bcfdfbf428cdb2396d463981ff7189564780849e3cd5908d69f012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b02473044022079aa2f98a0c79777c2a84f645e3ff545905bd4922a0f5df453be82dce4ab9de8022069c00c284ce69d51602bb2aa8adbfe95e3b9a08a7431b1e998bab1769126f416012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b0247304402207856f184e0e65a7dfa579b3dd9b3558f435736af52362d5fc0f5f12572520e78022008ff9135b882a137fabb84d2bbe761e695959c7a3191b835079c11e71227b268012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b02473044022017817fc9f5ad96e7768b5c756756484f56f55848a985b58a023f0fdb9746df2a02206f8a5b04131b8cc0dd8e7a4371ee6cc1eaecf33a32fd77a70a820633d22955a7012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b024730440220587d32656ef570140fda6a7ab9f563fd1122f7d191289bfbe33f58172964709902200c42ce86d586932ccf8102516303cf0d29e3dffb72563a1a600bf6aa155d4f40012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b0247304402203a2c762d9c326a2ca5e7f1d708f8886c4fad79a75c1e04f38d1ad7a7294758610220389626c3514c2c777cac982aa1436c07b61b98445bef244ed2a04d49045b4a43012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b02473044022078b58ba735f8b734e63f4e57e755b29a6d02a0066a0a14c13282bbb6012d4dba02201a84fce24c88a9f61e2807a258fc2337a0dec38eb9d7312fe692187d8c098d70012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b024730440220280fd576b3c9c265ac0704b5bd45a8f08e39944e0fc8f3368a7bf6e9fe4e202d0220634996c41b7df4447c4058c319db024ec09a179c2d1bb745cea2f4ae65dadcc7012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b02473044022044c2c67b51d30f7599f00e2f6046208f64ba7b64ddd094c942e8ef513144ed1502206941270740f8b7fefdd06319703c5fe99c3d6680144ac37b37d89572f890bc2c012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b024730440220719b7b574de31a33024187df0e9c268223cfcd44ae8552b9e1f5161029b70b23022049c118a5f6675a7dd604e26661988982f6c0ac6d9a77210e9f2676badfea3d1b012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b02473044022049cef32d89f6ce52508c0fc3fe74efa29b10e1a10e125075d40d1124caa4379c0220614791b7ced14678742899172d0b21efe4096332f32228ada18a144b8ecd2d5c012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b024730440220061a61c5a227c5f1eed4b10bedf7695a391ad281be2ffba98f130eb12e9d27fe02207613032cf2b04a90678b6877ba10980742439a03a77a00cce4982855bec063cb012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b0247304402207b997ec796273c4a4ef781b7e7e6c4c20dc2797d15240dd6484b3aac823c46c702206c60fb8c96a3d50b12c745a6995c3882693baa400ce6049b299e0f420d216163012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b0247304402205e33d9d6caf6d3c2211e88288821caf758b428bcc94e3ab9f8fc26efb76939290220338af62c4a882c64a79586c660057b0fa6a25351b4c4ba280b1672ca290fd168012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b0247304402207953f613c7d2a0527d49bef0adf2c85888c84eb8de9e225c1fe34722ab763f3d02204c2229584e3a489ed7578abc07e9f26a6c8c9b81aa63db72001ffac960c551a9012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b024730440220363e9d8853f9e3ce83380041d9c02ecea84c363efb190ff6a825041eb80319d2022037e255b85e8a868f625ab7bed625c3bdec7a70a1462d30785a74c3d92a3ec818012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b024730440220536f7e54a30fd1df88d7c114b1df8b6e76e5de7b8a24e711a9eb49b823b8e36302201c5da3f94118e02548d29b163ee1c9961438c545844b0c8f1f21ab9a869dde14012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b02473044022057c3382beed2a42ff63fbf11b8b5dc4f74dcc5f9d4ee14bd970fabaf154e3eb702204e9c875259d0e583036dc70acb59a8bcc5b1308f7d075980b9c9a9e98c99f513012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b0247304402205d3f6d856e792dd612387770e69136e2ed56f34caa4089acb20c070b0aa7ae6202207bc27d181a23a7d1bf1f43d4369f5e95588abc1d1244c0995c87414cdf551c2e012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b024730440220797dbe4a22515d96a998d429ac84488be9872eb11e62a1e8b9b8d7d4e955acf20220602dabb8da40fb62d773df2b95eb97368aa997f270c0ef38b9bc81e0459bf655012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b0247304402200f3148cc0d4084a5b77177cebbe144a27f2eb192d305014033cf9ff60dccceae02201a84dd2193db3e78c46ed4582f81a0cea44ca017624a7bd9c5ea12ea8a67b409012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b02473044022040a3b3f1a9ebce718c1c85d3cc684b77b5eda300c29157891fd3d8d8efc4334102204f7fda6b13e935653bf6bacbe10bb15615543535f01b3d2f9379b490ce1b3f5c012102d6a3c2d0cf7904ab6af54d7c959435a452b24a63194e1c4e7c337d3ebbb3017b2f010000",
   "txid": "ecb68237cd743b4f3d2dd68245e8a4a6984eb10f73228f5d1b69274ae817b9b9",
   "channel_id": "b9b917e84a27691b5d8f22730fb14e98a6a4e84582d62d3d4f3b74cd3782b6ec",
   "outnum": 0
}

cli-reg -rpcwallet=default -generate 10
{
  "address": "bcrt1qc226jt7dwmt4a5paewrtmkczq0xfe24cychnv5",
  "blocks": [
    "71d816d34ab518b6684e0c92bc0daed31f005749259ce6a2a73905e6679daeea",
    "45f8d0c2098310ffcaf05be83bff012d00eee0cdf98af8c901a14f032b8f2050",
    "05346cd64a95a90d863c15cbd300f3bc3e9fcaab3181eecb006433d1997a5bf2",
    "3cff9d04b9dfccea8323da009cdc86cdd5d4c3b6c2a0d84c0d1a677a416aecf9",
    "5982f4dd4e8540ec6d9627417ac3167912c22a14ce030a463d28d1b1b92ac2ad",
    "7b2253933959675dc148e1893be1ee9cd75147075464fd749b81fa05b708f805",
    "0e670f2fc7c29d30a5996923ac322af0ebbea1885898dc58ca88d64191204266",
    "3498b23e9b7bfd1c75b6cf664c0d07cf90961392171d1b722b11fd14815e6d8a",
    "4adfb6d81a2fd773759af778145f60038b107027e826a98517f06c9523dab197",
    "3122bf12f4806ffc11cd5f83c6258f2add2d9628f1eb431140cc43df892f4b80"
  ]
}

clg-reg listfunds
{
   "outputs": [
      {
         "txid": "ecb68237cd743b4f3d2dd68245e8a4a6984eb10f73228f5d1b69274ae817b9b9",
         "output": 1,
         "value": 372483229280,
         "amount_msat": "372483229280000msat",
         "scriptpubkey": "00141b42e1fc7b1cd93a469fa67ed5eabf36ce354dd6",
         "address": "bcrt1qrdpwrlrmrnvn535l5eldt64lxm8r2nwkv0ruxq",
         "status": "confirmed",
         "blockheight": 304,
         "reserved": false
      }
   ],
   "channels": [
      {
         "peer_id": "02c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee5",
         "connected": true,
         "state": "CHANNELD_AWAITING_LOCKIN",
         "channel_sat": 16777215,
         "our_amount_msat": "16777215000msat",
         "channel_total_sat": 16777215,
         "amount_msat": "16777215000msat",
         "funding_txid": "48a530e9154a1d2f67ea73525e6cee8d3046a08fee2b2d11ba35493b90f4283b",
         "funding_output": 1
      },
      {
         "peer_id": "02c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee5",
         "connected": true,
         "state": "CHANNELD_NORMAL",
         "short_channel_id": "304x2x0",
         "channel_sat": 16777215,
         "our_amount_msat": "16777215000msat",
         "channel_total_sat": 16777215,
         "amount_msat": "16777215000msat",
         "funding_txid": "ecb68237cd743b4f3d2dd68245e8a4a6984eb10f73228f5d1b69274ae817b9b9",
         "funding_output": 0
      }
   ]
}
```

### PR DESCRIPTION
**Pull request by niftynei**
Mark outputs as coinbases; don't spend them until they're mature. 

Fixes #5564 
Fixes #5696

### CODE REVIEW

File: wallet/wallet.c [hunk 1]
```diff
@@ -501,6 +510,17 @@ static bool deep_enough(u32 maxheight, const struct utxo *utxo,
 		if (csv_free > current_blockheight)
 			return false;
 	}
+
+	/* If the utxo is a coinbase, we over-write the maxheight
+	 * to the coinbase maxheight (current - 99) */
+	if (utxo->is_in_coinbase) {
```
Comment (rustyrussell) [inline wallet/wallet.c:516]: Perhaps a helper "u32 utxo_is_immature(utxo, blockheight)"?  Returns 0 if it's mature, otherwise number of blocks until it will me?

File: wallet/walletrpc.c [hunk 2]
```diff
@@ -271,13 +272,16 @@ static void json_add_utxo(struct json_stream *response,
 	if (utxo->spendheight)
 		json_add_string(response, "status", "spent");
 	else if (utxo->blockheight) {
-		json_add_string(response, "status", "confirmed");
+		if (utxo->is_in_coinbase
+		    && *utxo->blockheight + 99 > current_height) {
+			json_add_string(response, "status", "immature");
+		} else
+			json_add_string(response, "status", "confirmed");
```
Comment (rustyrussell) [inline wallet/walletrpc.c:279]: And use helper here...

File: wallet/walletrpc.c [hunk 3]
```diff
@@ -884,7 +888,8 @@ static void sendpsbt_done(struct bitcoind *bitcoind UNUSED,
 	wallet_transaction_add(ld->wallet, sending->wtx, 0, 0);
 
 	/* Extract the change output and add it to the DB */
-	wallet_extract_owned_outputs(ld->wallet, sending->wtx, NULL, &change);
+	/* FIXME: what txindex? */
+	wallet_extract_owned_outputs(ld->wallet, sending->wtx, 1, NULL, &change);
```
Comment (rustyrussell) [inline wallet/walletrpc.c:892]: Exactly.

**Review by rustyrussell — CHANGES_REQUESTED** [review]

**Review by vincenzopalazzo — COMMENTED** [review]
ACK https://github.com/ElementsProject/lightning/pull/5664/commits/f9280cc1efd41ed688c29576e583ed77c8495bd1

Sorry for delay here but I only got the meaning of this while reading this issue https://github.com/ElementsProject/lightning/issues/5696

**Review by vincenzopalazzo — APPROVED** [review]
