### PR TITLE
lightningd: don't log the response of getlog command

### LINKED ISSUE #2467: Crash when calling 'getlog io' after about 15min
### Issue and Steps to Reproduce
I wanted to investigate another unexpected channel close (similar to  #2462) by looking at `io` log.
So I redirected `getlog io > logfile30_io` in the shell and for about 15min it was processing and then crashed (see log below).

Restarting c-lightning and calling `getlog io` crashes it again after about 15min.

### `getinfo` output
```
{
  "id": "02682020a37a3b5876b16bffbf0ac56d7f379695a5d273cf16ed0f35f18ab2dc98", 
  "alias": "LookBusy4", 
  "color": "026820", 
  "num_peers": 5, 
  "num_pending_channels": 0, 
  "num_active_channels": 4, 
  "num_inactive_channels": 1, 
  "address": [
    {
      "type": "ipv4", 
      "address": "x.x.x.x", 
      "port": 9735
    }
  ], 
  "binding": [
    {
      "type": "ipv4", 
      "address": "192.168.1.166", 
      "port": 9735
    }
  ], 
  "version": "v0.6.3rc1-276-g1dcc482", 
  "blockheight": 566847, 
  "network": "bitcoin", 
  "msatoshi_fees_collected": 0, 
  "fees_collected_msat": "0msat"
}
```

```
2019-03-13T05:59:00.701Z lightning_gossipd(22982): Received channel_update for channel 561018x1565x0/0 now ACTIVE was ACTIVE (from subdaemon)
2019-03-13T05:59:01.464Z lightningd(22970):jcon fd 26: Log pruned 121726 entries (mem 20971585 -> 3939838)
2019-03-13T05:59:02.261Z lightningd(22970):jcon fd 26: Log pruned 142045 entries (mem 20971540 -> 9680948)
... (snip)
2019-03-13T06:13:59.488Z lightningd(22970):jcon fd 26: Log pruned 148175 entries (mem 20971568 -> 10467626)
2019-03-13T06:14:00.206Z lightningd(22970):jcon fd 26: Log pruned 148176 entries (mem 20971571 -> 10469400)
2019-03-13T06:14:00.918Z lightningd(22970):jcon fd 26: Log pruned 147735 entries (mem 20971551 -> 10497907)
lightningd: Fatal signal 6 (version v0.6.3rc1-276-g1dcc482)
0x55ee3191fe17 crashdump
        common/daemon.c:40
0x7f9b98fef05f ???
        ???:0
0x7f9b98feefff ???
        ???:0
0x7f9b98ff0429 ???
        ???:0
0x55ee3196e9aa call_error
        ccan/ccan/tal/tal.c:93
0x55ee3196fd3e tal_resize_
        ccan/ccan/tal/tal.c:696
0x55ee318f7f06 membuf_tal_realloc
        lightningd/json_stream.c:46
0x55ee31965d70 membuf_prepare_space_
        ccan/ccan/membuf/membuf.c:45
0x55ee318f818e mkroom
        lightningd/json_stream.c:103
0x55ee318f834f json_stream_append_vfmt
        lightningd/json_stream.c:148
0x55ee318f8493 json_stream_append_fmt
        lightningd/json_stream.c:165
0x55ee318f8658 json_start_member
        lightningd/json_stream.c:212
0x55ee318f8985 json_add_member
        lightningd/json_stream.c:273
0x55ee318f7a7a json_add_string
        lightningd/json.c:294
0x55ee318fed70 log_to_json
        lightningd/log.c:688
0x55ee318fdd0f log_each_line_
        lightningd/log.c:345
0x55ee318fee11 json_add_log
        lightningd/log.c:706
0x55ee318ff0c7 json_getlog
        lightningd/log.c:756
0x55ee318fa04b parse_request
        lightningd/jsonrpc.c:616
0x55ee318fa474 read_json
        lightningd/jsonrpc.c:714
0x55ee31960793 next_plan
        ccan/ccan/io/io.c:59
0x55ee319612af do_plan
        ccan/ccan/io/io.c:395
0x55ee319612ed io_ready
        ccan/ccan/io/io.c:405
0x55ee31962ec8 io_loop
        ccan/ccan/io/poll.c:310
0x55ee318fcb60 main
        lightningd/lightningd.c:829
0x7f9b98fdc2e0 ???
        ???:0
0x55ee318e6199 ???
        ???:0
0xffffffffffffffff ???
        ???:0
2019-03-13T06:14:01.621Z lightningd(22970): FATAL SIGNAL 6 (version v0.6.3rc1-276-g1dcc482)
2019-03-13T06:14:01.621Z lightningd(22970): backtrace: common/daemon.c:45 (crashdump) 0x55ee3191fe6b
2019-03-13T06:14:01.621Z lightningd(22970): backtrace: (null):0 ((null)) 0x7f9b98fef05f
2019-03-13T06:14:01.621Z lightningd(22970): backtrace: (null):0 ((null)) 0x7f9b98feefff
2019-03-13T06:14:01.621Z lightningd(22970): backtrace: (null):0 ((null)) 0x7f9b98ff0429
2019-03-13T06:14:01.621Z lightningd(22970): backtrace: ccan/ccan/tal/tal.c:93 (call_error) 0x55ee3196e9aa
2019-03-13T06:14:01.621Z lightningd(22970): backtrace: ccan/ccan/tal/tal.c:696 (tal_resize_) 0x55ee3196fd3e
2019-03-13T06:14:01.621Z lightningd(22970): backtrace: lightningd/json_stream.c:46 (membuf_tal_realloc) 0x55ee318f7f06
2019-03-13T06:14:01.621Z lightningd(22970): backtrace: ccan/ccan/membuf/membuf.c:45 (membuf_prepare_space_) 0x55ee31965d70
2019-03-13T06:14:01.621Z lightningd(22970): backtrace: lightningd/json_stream.c:103 (mkroom) 0x55ee318f818e
2019-03-13T06:14:01.621Z lightningd(22970): backtrace: lightningd/json_stream.c:148 (json_stream_append_vfmt) 0x55ee318f834f
2019-03-13T06:14:01.621Z lightningd(22970): backtrace: lightningd/json_stream.c:165 (json_stream_append_fmt) 0x55ee318f8493
2019-03-13T06:14:01.621Z lightningd(22970): backtrace: lightningd/json_stream.c:212 (json_start_member) 0x55ee318f8658
2019-03-13T06:14:01.621Z lightningd(22970): backtrace: lightningd/json_stream.c:273 (json_add_member) 0x55ee318f8985
2019-03-13T06:14:01.621Z lightningd(22970): backtrace: lightningd/json.c:294 (json_add_string) 0x55ee318f7a7a
2019-03-13T06:14:01.621Z lightningd(22970): backtrace: lightningd/log.c:688 (log_to_json) 0x55ee318fed70
2019-03-13T06:14:01.621Z lightningd(22970): backtrace: lightningd/log.c:345 (log_each_line_) 0x55ee318fdd0f
2019-03-13T06:14:01.621Z lightningd(22970): backtrace: lightningd/log.c:706 (json_add_log) 0x55ee318fee11
2019-03-13T06:14:01.621Z lightningd(22970): backtrace: lightningd/log.c:756 (json_getlog) 0x55ee318ff0c7
2019-03-13T06:14:01.621Z lightningd(22970): backtrace: lightningd/jsonrpc.c:616 (parse_request) 0x55ee318fa04b
2019-03-13T06:14:01.621Z lightningd(22970): backtrace: lightningd/jsonrpc.c:714 (read_json) 0x55ee318fa474
2019-03-13T06:14:01.621Z lightningd(22970): backtrace: ccan/ccan/io/io.c:59 (next_plan) 0x55ee31960793
2019-03-13T06:14:01.621Z lightningd(22970): backtrace: ccan/ccan/io/io.c:395 (do_plan) 0x55ee319612af
2019-03-13T06:14:01.621Z lightningd(22970): backtrace: ccan/ccan/io/io.c:405 (io_ready) 0x55ee319612ed
2019-03-13T06:14:01.621Z lightningd(22970): backtrace: ccan/ccan/io/poll.c:310 (io_loop) 0x55ee31962ec8
2019-03-13T06:14:01.621Z lightningd(22970): backtrace: lightningd/lightningd.c:829 (main) 0x55ee318fcb60
2019-03-13T06:14:01.621Z lightningd(22970): backtrace: (null):0 ((null)) 0x7f9b98fdc2e0
2019-03-13T06:14:01.621Z lightningd(22970): backtrace: (null):0 ((null)) 0x55ee318e6199
2019-03-13T06:14:01.621Z lightningd(22970): backtrace: (null):0 ((null)) 0xffffffffffffffff
Log dumped in crash.log.20190313061401
```

### PR DESCRIPTION
**Pull request by SimonVrouwe**
Before this, the response of `getlog io` would blow up quickly
when called multiple times.

closes #2467

### CODE REVIEW

**Comment by m-schmoock** [comment]
I tested, it works and doesn't break tests.

**Note**: Only applies if `log-level` is already `io`.

**Comment by m-schmoock** [comment]
ACK 6f4f61d

**Comment by SimonVrouwe** [comment]
@m-schmoock Thanks for the quick test.

> Note: Only applies if log-level is already io

Not sure what you mean by that, on my system `getlog io` blew up even with default `log-level=info`.

File: lightningd/jsonrpc.c [hunk 1]
```diff
@@ -531,6 +531,12 @@ struct json_stream *json_stream_success(struct command *cmd)
 	return r;
 }
 
+struct json_stream *json_stream_success_no_log(struct command *cmd)
+{
+	cmd->jcon->log = NULL;
```
Comment (cdecker) [inline lightningd/jsonrpc.c]: Aren't you going to re-enable logging at some point? `json_start` seems like a good candidate to ensure we have a logger in place.

Comment (m-schmoock) [reply lightningd/jsonrpc.c]: I shouldn't use ACK so quickly

Comment (ZmnSCPxj) [reply lightningd/jsonrpc.c]: Does this not suggest that a per-`json_stream` flag is more appropriate?  This may affect other pieces of code.

Comment (rustyrussell) [reply lightningd/jsonrpc.c]: Note that 0.7.1 already has logic to truncate things which would take > 1/64 of the buffer from commit 87cd628f5244b9cb0ca380c06c58722854dfa28c (aka v0.7.0-137-g87cd628f5):

```
	/* Don't immediately fill buffer with giant IOs */
	if (len > log->lr->max_mem / 64) {
		l->skipped++;
		len = log->lr->max_mem / 64;
	}
```

This should fix the crash in this case anyway.

Skipping logging is always kind of dangerous, IMHO, since it leaves blind spots.  If we really want this change, we need to:

1. Print an IO level message telling it that we're not going to log the getlog, eg. "log_io(jcon->log, LOG_IO_OUT, "Suppressing logging", NULL, 0);" and another one
when we reenable.
2. Add `json_stream_log_suppress(const char *msg);` and call it from json_getlog() to disable, and then reenable in json_stream_output_write() where it calls reader_cb (which implies it's sent all the output).

Comment (trueptolemy) [reply lightningd/jsonrpc.c]: emm, compares with#2467 , this commit [3dd4795](https://github.com/ElementsProject/lightning/commit/6cac2c959e41011b73a2452f1345eca0abd7d093) has reduced the number of log entries generated during `getlog io` process

Comment (SimonVrouwe) [reply lightningd/jsonrpc.c]: > Aren't you going to re-enable logging at some point?

Yes your right, I guess it worked here because the `json_connection` got closed after every command and then initialized (with log enabled) when opened again. But we cannot rely on that.

> Does this not suggest that a per-json_stream flag is more appropriate?

Exactly, then we don't touch `jcon->log` but only this specific [out] stream.

**Comment by SimonVrouwe** [comment]
Thanks for all the feedback!

Force-pushed another solution, now it suppresses logging _only_ for `getlog`'s particular `json_stream`. 

It uses 2-step approach to reach into low-level `json_stream` (and maintain encapsulation) and little a guard against misuse.

> has reduced the number of log entries generated during getlog io process

@trueptolemy Should now exactly match the number of entries as before this PR, except that `getlog's` [OUT] entry is replaced with: `...Suppressing logging of getlog command[OUT]`.

**Comment by cdecker** [comment]
ACK https://github.com/ElementsProject/lightning/pull/2656/commits/0c7879b01739280002750a5d96328cd25f3bde50

**Comment by rustyrussell** [comment]
Nice work!
