### PR TITLE
Let channeld add the outgoing channel as soon as funding locked on both sides

### LINKED ISSUE #284: Unable to see a channel and to find routes after the funding transaction is confirmed.
Me and MyFriend are trying to setup a payment channel in the testnet using this c-lightning implementation (code at master), but we are actually experiencing few issues. 

I opened a channel using the instruction:

```
cli/lightning-cli fundchannel 0234722de6b30b42e78f2f61970f614335f96f0e5ec3ef30fd36a0750ac2c3295f 10000000
```
where 0234722de6b30b42e78f2f61970f614335f96f0e5ec3ef30fd36a0750ac2c3295f is the id of MyFriend.

We waited for the transaction confirmation in testnet. The transaction was confirmed, as shown by the blockexplorer, at https://live.blockcypher.com/btc-testnet/tx/8a5aa8cd9f64f986a95f3ea788553189570d13a7f80d5ded39d630dcf18ade06/

Everything was working fine, in fact a call to the getpeers returns a CHANNELD_NORMAL state.

```
{ "peers" : [ 
    { "unique_id" : 3, 
    "state" : "CHANNELD_NORMAL", 
    "netaddr" : "::ffff:47.91.92.125:43266", 
    "peerid" : "0234722de6b30b42e78f2f61970f614335f96f0e5ec3ef30fd36a0750ac2c3295f", 
    "connected" : true, 
    "owner" : "lightning_channeld", 
    "channel" : "1196170:6:1", 
    "msatoshi_to_us" : 10000000000, 
    "msatoshi_total" : 10000000000 } ] }
```

The problem is that both getchannels and getnodes return empty set and getroute says that it's impossible to find a route. We tried to restart the nodes, but the channel never appears. Are we missing something?

At this link you can find the output of some instructions that MyFriend executed (the other side of the channel):
https://pastebin.com/raw/FsswXfE2

Moreover, we are experiencing crashes at both sides, in particular when MyFriend tries to fund another channel. This is the crash log.
https://mega.nz/#!04sCTbRL!Z1vA-LyL4i7bvT5DCcDlJzu5NCZimdzYUMZYEyVqI6A

If you need more information, we can provide them to you.

Best!

### PR DESCRIPTION
**Pull request by cdecker**
This is an alternative to #414. The main difference is that instead of having unsigned `channel_announcement` and `channel_update` messages that are allowed through if they are local, we add a new message that `channeld` can send to `gossipd` when both sides lock. This message now contains only the necessary information for the outgoing direction, and will immediately activate the channel so we can use it.

Fixes #284 
Depends on #413 (only the last 4 commits are for this PR, all others are from #413)

### CODE REVIEW

**Comment by cdecker** [comment]
Rebased on top of master now that #413 is merged.

File: gossipd/gossip.c [hunk 1]
```diff
@@ -1552,7 +1614,11 @@ static struct io_plan *recv_req(struct io_conn *conn, struct daemon_conn *master
 	case WIRE_GOSSIP_GET_UPDATE:
 	case WIRE_GOSSIP_GET_UPDATE_REPLY:
 	case WIRE_GOSSIP_SEND_GOSSIP:
-	break;
+		break;
+
+	/* Sent from channeld through its gossip_fd */
+	case WIRE_GOSSIP_LOCAL_ADD_CHANNEL:
+		break;
 	}
```
Comment (rustyrussell) [inline gossipd/gossip.c]: This is deeply confusing.

Just remove gossip_local_add_channel and the weird call to it: the "break;" here does exactly what we want if the master sends us that message for some reason.

**Comment by cdecker** [comment]
Great, thanks for the review @rustyrussell, I added a fixup and I'll squash and merge if you're ok with it

File: gossipd/gossip.c (hunk 1 above)
Comment (cdecker) [reply gossipd/gossip.c]: Oh wow, seems I botched up a rebase somewhere, sorry about that
