### PR TITLE
autoclean: Fix a null-pointer derefence when checking HTLC age

### LINKED ISSUE #5731: Autoclean v22.11rc2 crashes at start
### Issue and Steps to Reproduce
Every time the autoclean is automatically started, it crashes. I cannot see anything useful in lightningd log.

Backtrace from my system logs:

```
Nov 23 12:15:01 devzorln lightningd[122642]: autoclean: FATAL SIGNAL 11 (version v22.11rc2)
Nov 23 12:15:01 devzorln lightningd[122642]: 0x555a4102afea send_backtrace
Nov 23 12:15:01 devzorln lightningd[122642]: #011common/daemon.c:33
Nov 23 12:15:01 devzorln lightningd[122642]: 0x555a4102b084 crashdump
Nov 23 12:15:01 devzorln lightningd[122642]: #011common/daemon.c:46
Nov 23 12:15:01 devzorln lightningd[122642]: 0x7f0a5618f08f ???
Nov 23 12:15:01 devzorln lightningd[122642]: #011???:0
Nov 23 12:15:01 devzorln lightningd[122642]: 0x555a4101854f listforwards_done
Nov 23 12:15:01 devzorln lightningd[122642]: #011plugins/autoclean.c:327
Nov 23 12:15:01 devzorln lightningd[122642]: 0x555a4101cfda handle_rpc_reply
Nov 23 12:15:01 devzorln lightningd[122642]: #011plugins/libplugin.c:768
Nov 23 12:15:01 devzorln lightningd[122642]: 0x555a4101d15a rpc_read_response_one
Nov 23 12:15:01 devzorln lightningd[122642]: #011plugins/libplugin.c:943
Nov 23 12:15:01 devzorln lightningd[122642]: 0x555a4101d1fc rpc_conn_read_response
Nov 23 12:15:01 devzorln lightningd[122642]: #011plugins/libplugin.c:967
Nov 23 12:15:01 devzorln lightningd[122642]: 0x555a4109c3ab next_plan
Nov 23 12:15:01 devzorln lightningd[122642]: #011ccan/ccan/io/io.c:59
Nov 23 12:15:01 devzorln lightningd[122642]: 0x555a4109c878 do_plan
Nov 23 12:15:01 devzorln lightningd[122642]: #011ccan/ccan/io/io.c:407
Nov 23 12:15:01 devzorln lightningd[122642]: 0x555a4109c915 io_ready
Nov 23 12:15:01 devzorln kernel: [50776.417553] autoclean[122642]: segfault at 0 ip 0000000000000000 sp 00007ffec617ff88 error 14 in autoclean[555a41013000+4000]
Nov 23 12:15:01 devzorln kernel: [50776.417558] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
Nov 23 12:15:01 devzorln lightningd[122642]: #011ccan/ccan/io/io.c:417
Nov 23 12:15:01 devzorln lightningd[122642]: 0x555a4109db51 io_loop
Nov 23 12:15:01 devzorln lightningd[122642]: #011ccan/ccan/io/poll.c:453
Nov 23 12:15:01 devzorln lightningd[122642]: 0x555a4101d43e plugin_main
Nov 23 12:15:01 devzorln lightningd[122642]: #011plugins/libplugin.c:1800
Nov 23 12:15:01 devzorln lightningd[122642]: 0x555a410192c7 main
Nov 23 12:15:01 devzorln lightningd[122642]: #011plugins/autoclean.c:604
Nov 23 12:15:01 devzorln lightningd[122642]: 0x7f0a56170082 ???
Nov 23 12:15:01 devzorln lightningd[122642]: #011???:0
Nov 23 12:15:01 devzorln lightningd[122642]: 0x555a41017cad ???
Nov 23 12:15:01 devzorln lightningd[122642]: #011???:0
Nov 23 12:15:01 devzorln lightningd[122642]: 0xffffffffffffffff ???
Nov 23 12:15:01 devzorln lightningd[122642]: #011???:0
```

### PR DESCRIPTION
**Pull request by cdecker**
The autoclean plugin would assume we have a `resolved_time` which may not be true for oldish nodes that predate our annotations.

Changelog-None Unreleased change

Reported-by: <@devastgh>

Fixes #5731

### CODE REVIEW

File: plugins/autoclean.c [hunk 1]
```diff
@@ -324,6 +324,14 @@ static struct command_result *listforwards_done(struct command *cmd,
 			continue;
 		}
 
+		/* Check if we have a resolved_time, before making a
+		 * decision on it. This is possible in older nodes
+		 * that predate our annotations for forwards.*/
+		if (json_get_member(buf, t, "resolved_time") == NULL) {
```
Comment (vincenzopalazzo) [inline plugins/autoclean.c:330]:
```suggestion
		if (!json_get_member(buf, t, "resolved_time")) {
```

There is any reason that I'm ignoring to use of this shortcut?

**Review by vincenzopalazzo — APPROVED** [review]
ACK https://github.com/ElementsProject/lightning/pull/5732/commits/fa6d712b5dd880576d2d68bff18cc0d2ec0a3a8e

File: plugins/autoclean.c (hunk 1 above)
Comment (cdecker) [reply plugins/autoclean.c:330]: I personally prefer being very explicit in these cases, since I often end up not seeing the `!` in front when reading code :-)

**Review by rustyrussell — APPROVED** [review]
Ack https://github.com/ElementsProject/lightning/pull/5732/commits/fa6d712b5dd880576d2d68bff18cc0d2ec0a3a8e
