### PR TITLE
JSON-RPC: Fix unquoted error string when parser fails

### LINKED ISSUE #963: JSONRPC error messages are not properly quoted
Some error messages are not properly quoted:

```
--> {}
<-- { "jsonrpc": "2.0",  "error" : { "code" : -32600, "message" : No id }, "id" : null }

--> {"id":null}
<-- { "jsonrpc": "2.0",  "error" : { "code" : -32600, "message" : Expected string/primitive for id }, "id" : null }
```

But others are:

```
--> {"id":"1","method":"xyz"}
<-- { "jsonrpc": "2.0",  "error" : { "code" : -32600, "message" : "No params" }, "id" : "1" }

--> {"id":"1","method":"xyz","params":[]}
<-- { "jsonrpc": "2.0",  "error" : { "code" : -32601, "message" : "Unknown command 'xyz'" }, "id" : "1" }
```

### PR DESCRIPTION
**Pull request by cdecker**
Fixes #963

### CODE REVIEW

File: lightningd/jsonrpc.c [hunk 1]
```diff
@@ -429,9 +429,8 @@ static void json_command_malformed(struct json_connection *jcon,
 				   const char *id,
 				   const char *error)
 {
-	return connection_result(jcon, id, NULL, error,
-				 JSONRPC2_INVALID_REQUEST,
-				 NULL);
+	return connection_result(jcon, id, NULL, tal_fmt(jcon, "\"%s\"", error),
```
Comment (ZmnSCPxj) [inline lightningd/jsonrpc.c]: Would not this leak? Client applications might keep the `jcon` alive indefinitely. Of course, arguably an application should not trigger this code.

Arguably we should be using `json_add_string` somehow, which performs proper escaping, but I suppose this is okay.

Comment (rustyrussell) [reply lightningd/jsonrpc.c]: True.  We could make connection_result build the JSON response using primitives rather than manually...

But note that the other caller to connection_result() which has non-null error also does quoting manually.  We should do this inside connection_result()!

File: lightningd/jsonrpc.c [hunk 2]
```diff
@@ -237,48 +237,58 @@ static const struct json_command *find_cmd(const char *buffer,
...
+				      const char *errmsg,
+				      int code,
+				      const struct json_result *data)
+{
+	/* Use this to escape errmsg. */
+	struct json_result *errorres = new_json_result(jcon);
+	const char *data_str;
+
+	json_add_string_escape(errorres, NULL, errmsg);
+	if (data)
```
Comment (ZmnSCPxj) [inline lightningd/jsonrpc.c]: The code here somewhat misleadingly makes it appear that `data_str` is somehow related to `errorres`: they are in the same "paragraph" of code, and `data_str` is allocated with `errorres` as parent.

Maybe "cleaner" with a `tal_tmpctx` locally that parents both `errorres` and `data_str`.

**Comment by ZmnSCPxj** [comment]
ACK e24ceb8cce3c8eda7e25b439814bb3b7974e6882

**Comment by cdecker** [comment]
ACK e24ceb8
