### PR TITLE
Stabilize a number of flaky tests and fix some gossip semantics while we're at it

### LINKED ISSUE #1515: Travis should test in parallel
Our tests run much faster in parallel, particularly due to polling delays, etc.  I run -n10 on my laptop (without valgrind) with no problems.

That would allow us to re-enable some non-developer tests, for example.

### PR DESCRIPTION
**Pull request by cdecker**
The flaky pruning tests were really annoying, so I took a closer look at them. It turns out that we were relying on a `channel_update` being sent before actually closing the connection, otherwise we were not disabling both directions.

This now explicitly disables both directions on close, and on disconnect. While not a big issue before, with the `r` fields being merged soon, we could end up sending a disabled channel as a `contact_point` if we didn't disable them.

Other changes include better handling of concurrent opens and watching to logs for the wrong signals, and filtering out some output (looking at you Fee Estimator)

Fixes #1515 since I now feel much better about the test stability.

### CODE REVIEW

File: lightningd/closing_control.c [hunk 1]
```diff
@@ -213,4 +213,11 @@ void peer_start_closingd(struct channel *channel,
 	/* We don't expect a response: it will give us feedback on
 	 * signatures sent and received, then closing_complete. */
 	subd_send_msg(channel->owner, take(initmsg));
+
+	/* Now tell gossipd that we're closing and that neither direction should
+	 * be used. */
+	if (channel->scid)
+		subd_send_msg(channel->peer->ld->gossip,
+			      take(towire_gossip_local_channel_close(
+				  tmpctx, channel->scid)));
```
Comment (rustyrussell) [inline lightningd/closing_control.c]: Minor nit: take() should be generally done from something off NULL if it's transitory; no need to use tmpctx here.  That means that if take() doesn't work for some reason we see the leak.

File: gossipd/gossip.c [hunk 2]
```diff
@@ -2496,8 +2496,9 @@ static struct io_plan *handle_disable_channel(struct io_conn *conn,
 	if (timestamp <= hc->last_timestamp)
 		timestamp = hc->last_timestamp + 1;
 
-	/* Active is bit 1 << 1, mask and apply */
-	flags = (0xFFFD & flags) | (!active << 1);
+	flags = direction;
+	if (!active)
+		flags |= ROUTING_FLAGS_DISABLED;
```
Comment (rustyrussell) [inline gossipd/gossip.c]: How does this "fix" it?  It's neater, sure, but it should give the same effect?

File: gossipd/gossip.c [hunk 3]
```diff
@@ -2355,11 +2355,99 @@ static struct io_plan *peer_important(struct io_conn *conn,
...
+	}
+
+	err = handle_channel_update(rstate, msg, "disable_channel");
+	if (err)
+		status_failed(STATUS_FAIL_INTERNAL_ERROR,
+			      "rejected disabling channel_update: %s",
+			      tal_hex(tmpctx, err));
+}
+
+static void peer_disable_channels(struct routing_state *rstate, struct node *node)
```
Comment (rustyrussell) [inline gossipd/gossip.c]:
~~~This function *actually* disables 0 or 1 channel,, between us and this peer.   It does so redundantly, since the callers already set the DISABLED flag.  The 'gossip_disable_channel' also assumes we're one end of the channel (and doesn't assert it).~~~

~~~Perhaps neater to call this "disable_channel" and have it set both disabled flags, then if one side is us, send an update.~~~ (Cleaned up in later commit, great work!)

I prefer not to touch the flags word if the halfchan is not defined, either, though valgrind won't complain.

File: gossipd/gossip.c [hunk 4]
```diff
@@ -2375,6 +2463,11 @@ static struct io_plan *peer_disconnected(struct io_conn *conn,
 	status_trace("Forgetting remote peer %s",
 		     type_to_string(tmpctx, struct pubkey, &peer->id));
 
+	/* Disable any channels to and from this peer */
```
Comment (rustyrussell) [inline gossipd/gossip.c]: And we should not do this if we this is caused by a reconnecting peer (below in this function).  Though I have a patch WIP which sets up a timer for every channel_update so we don't spam updates, which would also cover this.

File: gossipd/gossip.c [hunk 5]
```diff
@@ -2394,6 +2394,11 @@ static void gossip_disable_channel(struct routing_state *rstate, struct chan *ch
 		    "Unable to parse previously accepted channel_update");
 	}
 
+	/* Avoid sending gratuitous disable messages, e.g., on close and
+	 * subsequent disconnect */
+	if (flags & ROUTING_FLAGS_DISABLED)
+		return;
+
```
Comment (rustyrussell) [inline gossipd/gossip.c]: I have the same patch in my queue, though I genericised it (so any "no-change" update gets suppressed except keepalives), but this is still a good change.

File: gossipd/gossip.c [hunk 6]
```diff
@@ -1900,6 +1900,26 @@ static void gossip_disable_channel(struct routing_state *rstate, struct chan *ch
...
+	    get_node(daemon->rstate, &daemon->rstate->local_id);
+	struct chan *c;
+	size_t i;
+
+	/* We don't have a local_node, so we don't have any channels yet
+	 * either */
+	if (!local_node)
+		return;
+
+	for (i=0; i<tal_count(local_node->chans); i++) {
```
Comment (rustyrussell) [inline gossipd/gossip.c]: Mildly prefer `for (size_t i` these days; also `c` can go inside loop.

File: tests/utils.py [hunk 7]
```diff
@@ -338,12 +338,22 @@ def __init__(self, daemon, rpc, btc, executor, may_fail=False, may_reconnect=Fal
...
+
+        if confirm or announce:
+            self.bitcoin.generate_block(1)
+
+        if announce:
+            self.bitcoin.generate_block(5)
+
+        if confirm or announce:
+            self.daemon.wait_for_log(
+                r'Funding tx {} depth'.format(fundingtx['txid']))
```
Comment (rustyrussell) [inline tests/utils.py]: But we don't actually wait for announce?  Should we do something like:

```python
if announce:
    blocks = 6
elif confirm:
    blocks = 1
else
    blocks = None

if blocks:
    bitcoind.generate_block(blocks)
    self.daemon.wait_for_log('Funding tx {} depth {}'.format(fundingtx['txid'], blocks)
```

File: Makefile [hunk 8]
```diff
@@ -367,7 +367,7 @@ update-mocks/%: %
 	@tools/update-mocks.sh "$*"
 
 unittest/%: %
-	$(VALGRIND) $(VALGRIND_TEST_ARGS) $*
+	$(VALGRIND) $(VALGRIND_TEST_ARGS) $* > /dev/null
```
Comment (rustyrussell) [inline Makefile]: Mildly prefer redirecting to tmpfile and dumping the output if it fails, but that's more code...
