### PR TITLE
Onchaind replay different txs

### LINKED ISSUE #1114: Consistent crash "FATAL SIGNAL 11 RECEIVED" after catch-up
My daemon is consistently crashing since a few days after having caught up with the blockchain. I have pulled the latest updates and rebuilt several times. Last crash was at commit 58fae47.

crash.log:
```
+14186.849070555 lightningd(9833):DEBUG: Adding block 511107: 0000000000000000001845d43505e86dde6bdbf55fce9b8325d9619a2200901c
+14189.756722369 lightning_gossipd(9841):DEBUG: Received channel_update for channel 510308:736:0(0) now ACTIVE
+14189.756828585 lightning_gossipd(9841):DEBUG: Received channel_update for channel 509559:411:0(0) now ACTIVE
+14189.756915298 lightning_gossipd(9841):DEBUG: Received channel_update for channel 506088:2414:0(0) now ACTIVE
+14189.756972321 lightning_gossipd(9841):DEBUG: Received channel_update for channel 507064:1108:1(1) now ACTIVE
+14189.830532269 lightningd(9833):BROKEN: FATAL SIGNAL 11 RECEIVED
+14189.841756223 lightningd(9833):BROKEN: backtrace: lightningd/log.c:504 (log_crash) 0x414f40
+14189.841841556 lightningd(9833):BROKEN: backtrace: (null):0 ((null)) 0x7f0eba0d84af
+14189.841877372 lightningd(9833):BROKEN: backtrace: (null):0 ((null)) 0x7f0eba0f1cc0
+14189.841900682 lightningd(9833):BROKEN: backtrace: (null):0 ((null)) 0x7f0eba119a48
+14189.842038474 lightningd(9833):BROKEN: backtrace: ccan/ccan/tal/str/str.c:67 (do_vfmt) 0x46a61c
+14189.842068225 lightningd(9833):BROKEN: backtrace: ccan/ccan/tal/str/str.c:91 (tal_vfmt) 0x46a6dc
+14189.842103494 lightningd(9833):BROKEN: backtrace: lightningd/log.c:264 (logv) 0x41435a
+14189.842128505 lightningd(9833):BROKEN: backtrace: lightningd/log.c:320 (log_) 0x4146da
+14189.842471909 lightningd(9833):BROKEN: backtrace: lightningd/peer_control.c:534 (funding_lockin_cb) 0x421a16
+14189.842679274 lightningd(9833):BROKEN: backtrace: lightningd/watch.c:221 (txw_fire) 0x429d4f
+14189.842701448 lightningd(9833):BROKEN: backtrace: lightningd/watch.c:289 (watch_topology_changed) 0x429fb3
+14189.842977929 lightningd(9833):BROKEN: backtrace: lightningd/chaintopology.c:335 (updates_complete) 0x406ed1
+14189.842997248 lightningd(9833):BROKEN: backtrace: lightningd/chaintopology.c:429 (get_new_block) 0x407346
+14189.843299464 lightningd(9833):BROKEN: backtrace: lightningd/bitcoind.c:657 (process_getblockhash) 0x405535
+14189.843319911 lightningd(9833):BROKEN: backtrace: lightningd/bitcoind.c:186 (bcli_finished) 0x403fb7
+14189.843485216 lightningd(9833):BROKEN: backtrace: ccan/ccan/io/poll.c:183 (destroy_conn) 0x4610b1
+14189.843503984 lightningd(9833):BROKEN: backtrace: ccan/ccan/io/poll.c:189 (destroy_conn_close_fd) 0x4610d1
+14189.843773033 lightningd(9833):BROKEN: backtrace: ccan/ccan/tal/tal.c:240 (notify) 0x46b720
+14189.843791471 lightningd(9833):BROKEN: backtrace: ccan/ccan/tal/tal.c:400 (del_tree) 0x46bbd1
+14189.843829697 lightningd(9833):BROKEN: backtrace: ccan/ccan/tal/tal.c:509 (tal_free) 0x46bfe4
+14189.844019283 lightningd(9833):BROKEN: backtrace: ccan/ccan/io/io.c:443 (io_close) 0x45fd39
+14189.844038381 lightningd(9833):BROKEN: backtrace: ccan/ccan/io/poll.c:314 (io_loop) 0x4614c0
+14189.844248188 lightningd(9833):BROKEN: backtrace: lightningd/lightningd.c:403 (main) 0x413644
+14189.844266654 lightningd(9833):BROKEN: backtrace: (null):0 ((null)) 0x7f0eba0c382f
+14189.844371345 lightningd(9833):BROKEN: backtrace: (null):0 ((null)) 0x4033f8
+14189.844388414 lightningd(9833):BROKEN: backtrace: (null):0 ((null)) 0xffffffffffffffff
```

stdout:
```
2018-02-27T05:55:47.283Z lightningd(9833): 0273081ce642554d5a68a5236564fe88a3783457dc09e52812517f5724f36daefd chan #89: State changed from FUNDING_SPEND_SEEN to ONCHAIN
2018-02-27T05:59:00.167Z lightningd(9833): FATAL SIGNAL 11 RECEIVED
2018-02-27T05:59:00.178Z lightningd(9833): backtrace: lightningd/log.c:504 (log_crash) 0x414f40
2018-02-27T05:59:00.178Z lightningd(9833): backtrace: (null):0 ((null)) 0x7f0eba0d84af
2018-02-27T05:59:00.178Z lightningd(9833): backtrace: (null):0 ((null)) 0x7f0eba0f1cc0
2018-02-27T05:59:00.178Z lightningd(9833): backtrace: (null):0 ((null)) 0x7f0eba119a48
2018-02-27T05:59:00.178Z lightningd(9833): backtrace: ccan/ccan/tal/str/str.c:67 (do_vfmt) 0x46a61c
2018-02-27T05:59:00.178Z lightningd(9833): backtrace: ccan/ccan/tal/str/str.c:91 (tal_vfmt) 0x46a6dc
2018-02-27T05:59:00.178Z lightningd(9833): backtrace: lightningd/log.c:264 (logv) 0x41435a
2018-02-27T05:59:00.178Z lightningd(9833): backtrace: lightningd/log.c:320 (log_) 0x4146da
2018-02-27T05:59:00.178Z lightningd(9833): backtrace: lightningd/peer_control.c:534 (funding_lockin_cb) 0x421a16
2018-02-27T05:59:00.179Z lightningd(9833): backtrace: lightningd/watch.c:221 (txw_fire) 0x429d4f
2018-02-27T05:59:00.179Z lightningd(9833): backtrace: lightningd/watch.c:289 (watch_topology_changed) 0x429fb3
2018-02-27T05:59:00.179Z lightningd(9833): backtrace: lightningd/chaintopology.c:335 (updates_complete) 0x406ed1
2018-02-27T05:59:00.179Z lightningd(9833): backtrace: lightningd/chaintopology.c:429 (get_new_block) 0x407346
2018-02-27T05:59:00.179Z lightningd(9833): backtrace: lightningd/bitcoind.c:657 (process_getblockhash) 0x405535
2018-02-27T05:59:00.179Z lightningd(9833): backtrace: lightningd/bitcoind.c:186 (bcli_finished) 0x403fb7
2018-02-27T05:59:00.179Z lightningd(9833): backtrace: ccan/ccan/io/poll.c:183 (destroy_conn) 0x4610b1
2018-02-27T05:59:00.179Z lightningd(9833): backtrace: ccan/ccan/io/poll.c:189 (destroy_conn_close_fd) 0x4610d1
2018-02-27T05:59:00.180Z lightningd(9833): backtrace: ccan/ccan/tal/tal.c:240 (notify) 0x46b720
2018-02-27T05:59:00.180Z lightningd(9833): backtrace: ccan/ccan/tal/tal.c:400 (del_tree) 0x46bbd1
2018-02-27T05:59:00.180Z lightningd(9833): backtrace: ccan/ccan/tal/tal.c:509 (tal_free) 0x46bfe4
2018-02-27T05:59:00.180Z lightningd(9833): backtrace: ccan/ccan/io/io.c:443 (io_close) 0x45fd39
2018-02-27T05:59:00.180Z lightningd(9833): backtrace: ccan/ccan/io/poll.c:314 (io_loop) 0x4614c0
2018-02-27T05:59:00.180Z lightningd(9833): backtrace: lightningd/lightningd.c:403 (main) 0x413644
2018-02-27T05:59:00.180Z lightningd(9833): backtrace: (null):0 ((null)) 0x7f0eba0c382f
2018-02-27T05:59:00.180Z lightningd(9833): backtrace: (null):0 ((null)) 0x4033f8
2018-02-27T05:59:00.180Z lightningd(9833): backtrace: (null):0 ((null)) 0xffffffffffffffff
Fatal signal 11. 0x415026 log_crash
        lightningd/log.c:530
0x7f0eba0d84af ???
        ???:0
0x7f0eba0f1cc0 ???
        ???:0
0x7f0eba119a48 ???
        ???:0
0x46a61c do_vfmt
        ccan/ccan/tal/str/str.c:67
0x46a6dc tal_vfmt
        ccan/ccan/tal/str/str.c:91
0x41435a logv
        lightningd/log.c:264
0x4146da log_
        lightningd/log.c:320
0x421a16 funding_lockin_cb
        lightningd/peer_control.c:534
0x429d4f txw_fire
        lightningd/watch.c:221
0x429fb3 watch_topology_changed
        lightningd/watch.c:289
0x406ed1 updates_complete
        lightningd/chaintopology.c:335
0x407346 get_new_block
        lightningd/chaintopology.c:429
0x405535 process_getblockhash
        lightningd/bitcoind.c:657
0x403fb7 bcli_finished
        lightningd/bitcoind.c:186
0x4610b1 destroy_conn
        ccan/ccan/io/poll.c:183
0x4610d1 destroy_conn_close_fd
        ccan/ccan/io/poll.c:189
0x46b720 notify
        ccan/ccan/tal/tal.c:240
0x46bbd1 del_tree
        ccan/ccan/tal/tal.c:400
0x46bfe4 tal_free
        ccan/ccan/tal/tal.c:509
0x45fd39 io_close
        ccan/ccan/io/io.c:443
0x4614c0 io_loop
        ccan/ccan/io/poll.c:314
0x413644 main
        lightningd/lightningd.c:403
0x7f0eba0c382f ???
        ???:0
0x4033f8 ???
        ???:0
0xffffffffffffffff ???
        ???:0
Log dumped in crash.log
```

getinfo:
```
{ "id" : "036487e0bd981617c674c2856fc0050472a0182838e0a4a1a67545c6cdee9f49a0", "port" : 9735, "address" : 
	[ 
		{ "type" : "ipv4", "address" : "81.6.40.158", "port" : 9735 } ], "version" : "v0.5.2-2016-11-21-2125-g58fae47", "blockheight" : 510777, "network" : "bitcoin" }
```

### PR DESCRIPTION
**Pull request by rustyrussell**
This fixes #1114 with some other incidental cleanups along the way.

### CODE REVIEW

File: onchaind/onchain.c [hunk 1]
```diff
@@ -367,30 +367,80 @@ static void propose_resolution_at_block(struct tracked_output *out,
...
-	/* Not the same as what we proposed? */
-	if (!structeq(&out->resolved->txid, txid)) {
-		out->resolved = tal_free(out->resolved);
-		/* Don't need proposal any more */
-		out->proposal = tal_free(out->proposal);
+	/* Our proposal can change as feerates change.  Input
+	 * comparison (ignoring signatures) works pretty well.
+	 *
+	 * FIXME: Better would be to compare outputs, but they weren't
+	 * saved to db correctly until now. (COMPAT_V052)
```
Comment (ZmnSCPxj) [inline onchaind/onchain.c]: The comment suggests we should have a `#ifdef COMPAT_V052` or similar in the vicinity?

File: bitcoin/script.c [hunk 2]
```diff
@@ -214,6 +215,14 @@ u8 *scriptpubkey_p2pkh(const tal_t *ctx, const struct bitcoin_address *addr)
 	return script;
 }
 
+u8 *scriptpubkey_opreturn(const tal_t *ctx)
+{
+	u8 *script = tal_arr(ctx, u8, 0);
+
+	add_op(&script, OP_RETURN);
```
Comment (ZmnSCPxj) [inline bitcoin/script.c]: Does not standard `OP_RETURN` require an additional push after the `OP_RETURN`?  Otherwise the tx may not get broadcast across the Bitcoin network to reach a miner?

File: wallet/wallet.c [hunk 3]
```diff
@@ -701,6 +705,9 @@ u32 wallet_first_blocknum(struct wallet *w, u32 first_possible)
 		else
 			first_utxo = UINT32_MAX;
 	}
+#else
+	first_utxo = db_get_intvar(w->db, "last_processed_block", UINT32_MAX);
```
[the remark this answers is not in the document]
Comment (rustyrussell) [reply wallet/wallet.c]: No, first_possible is the first theoretical possibility for the blockchain.

first_utxo (could be called "first_unseen_utxo") is simply the last processed_block (plus one, but that would make this statement more complex).

File: onchaind/onchain.c (hunk 1 above)
Comment (rustyrussell) [reply onchaind/onchain.c]: It's in the FIXME as grep-fodder for COMPAT_V052.  I'm not sure we'll actually do this, but at least we'll have the chance to do so when we decided to delete all those....

File: bitcoin/script.c (hunk 2 above)
Comment (rustyrussell) [reply bitcoin/script.c]: bitcoind source doesn't seem to, but I added a test to be sure!

File: wallet/wallet.c (hunk 3 above)
[the remark this answers is not in the document]
Comment (ZmnSCPxj) [reply wallet/wallet.c]: Okay, I will have to trust you on that, as the tx scanning is beyond my capability for now.

File: bitcoin/script.c (hunk 2 above)
Comment (ZmnSCPxj) [reply bitcoin/script.c]: Where is test? I think regtest and testnet skip over `IsStandardTx` check?

The bitcoind source doesn't seem to indeed; it allows a plain `OP_RETURN`: https://github.com/bitcoin/bitcoin/blob/d889c036cd6f683116e6a27e404be2809d1deb76/src/script/standard.cpp#L88-L96

All the guides I found on the Internet indicate a single data push after `OP_RETURN` but the actual code seems to allow 0 to any number of data pushes, as long as the total length is below the limit.

**Comment by rustyrussell** [comment]
OK, fixed some CI-found errors, and added 4 new commits....

**Comment by rustyrussell** [comment]
More test errors: I had to fix the wallet COMPAT patch, as we weren't setting the last_processed_block variable on all cases.

File: onchaind/onchain.c [hunk 4]
```diff
@@ -243,10 +243,11 @@ static struct bitcoin_tx *tx_to_us(const tal_t *ctx,
 			 + 1 + 3 + 73 + 0 + tal_len(wscript))
 		/ 1000;
 
-	/* Result is trivial?  Just eliminate output. */
-	if (tx->output[0].amount < dust_limit_satoshis + fee)
-		tal_resize(&tx->output, 0);
-	else
+	/* Result is trivial?  Spent to OP_RETURN to avoid leaving dust. */
+	if (tx->output[0].amount < dust_limit_satoshis + fee) {
```
Comment (cdecker) [inline onchaind/onchain.c]: This solves the to_us respend issue when the value is below the fee I guess. Wouldn't it be better to not create that to_us output at all? But that'd require signaling to the peer that we're ok omitting our output in the commit, which is a spec change.

Comment (rustyrussell) [reply onchaind/onchain.c]: This is onchain-only: if fees rise and we can't spent, it's best to remove the UTXO.

The alternative would be to drop the feerate and cross our fingers (or consider it closed?).

For some outputs we're not in a hurry, it's just tidying up: they could potentially use a lower fee rate.

**Comment by rustyrussell** [comment]
Rebased to fix conflicts.

**Comment by cdecker** [comment]
Looks like we have just one include out of order, otherwise we're good to go :-)

**Comment by cdecker** [comment]
Rebased, fixed a minor conflict in the mocks of run-wallet and fixed header ordering.

@ZmnSCPxj if you could ack that there hasn't been a major change then I can merge this :-)

**Comment by ZmnSCPxj** [comment]
ACK 419d95abb05c24cc82fc676587df9b611e56da08
