### PR TITLE
Remember and spend unilateral close outputs

### LINKED ISSUE #385: Fail to withdraw funds
Hello,

I'm unable to withdraw funds received via a channel. I funded a channel between two nodes in a regtest, created and paid an invoice and successfully closed the channel.

Now I'm in the state:
```
  "peers": [ {
      "state": "ONCHAIND_MUTUAL",
      "netaddr": [],
      "peerid": "0306249dedc09e9c1926b143a42543118737070b6c05e3c52055a5f97679b3eed8",
      "connected": false,
      "channel": "1001:2:0",
      "msatoshi_to_us": 1000000000,
      "msatoshi_total": 10000000000
    }  ]
```
However, withdrawal of 1 satoshi ends up with an error:
`"Not enough funds available"`

I'm not sure whether it is a bug or I'm doing something wrong. Thank you for you help.

### PR DESCRIPTION
**Pull request by cdecker**
This should get us all the funds that we own back, on unilateral close, cheat and collaborative close. First we make sure to remember all outputs that we are interested in and store them in the DB. Special care needs to be taken for the unilateral_close:to_us output, since it's the only p2wpkh output which we don't use keyindex for. For this case we need to extend the output data to include the peer_id, channel_id and commitment_point.

This also refactors the funding and withdrawal transaction generation to let `hsmd` generate the full TX instead of just the signatures. This de-duplicates and simplifies the creation of these transaction since we no longer need to generate them in two separate parts and ensure that they are identical.

Fixes #385

### CODE REVIEW

File: lightningd/peer_control.c [hunk 1]
```diff
@@ -1280,7 +1280,30 @@ static void handle_irrevocably_resolved(struct peer *peer, const u8 *msg)
...
+		fatal("onchaind gave invalid add_utxo message: %s", tal_hex(msg, msg));
+	}
+
+	struct utxo *u = tal(msg, struct utxo);
+	u->is_p2sh = true;
+	u->txid = prev_out_tx;
+	u->outnum = prev_out_index;
+	u->keyindex = 0;
+	u->status = output_state_available;
+	u->amount = value;
```
Comment (rustyrussell) [inline lightningd/peer_control.c]: I would usually allocate first, initialize some fields, then directly pass fields to fromwire_onchain_add_utxo.  Minor though.

File: common/permute_tx.c [hunk 2]
```diff
@@ -121,7 +127,7 @@ void permute_outputs(struct bitcoin_tx_output *outputs, size_t num_outputs,
 	size_t i;
 
 	/* Now do a dumb sort (num_outputs is small). */
-	for (i = 0; i < num_outputs; i++) {
+	for (i = 0; i < num_outputs-1; i++) {
```
Comment (rustyrussell) [inline common/permute_tx.c]: This is the real fix, AFAICT.  The optimizing out the single case is unnecessary?

Comment (rustyrussell) [reply common/permute_tx.c]: And you should fix the num_inputs case as well...

File: wire/fromwire.c [hunk 3]
```diff
@@ -228,3 +228,7 @@ void derive_channel_id(struct channel_id *channel_id,
 	channel_id->id[sizeof(*channel_id)-1] ^= txout;
 }
 
+void fromwire_bitcoin_tx(const u8 **cursor, size_t *max, struct bitcoin_tx *tx)
+{
+	pull_bitcoin_tx_onto(tx, cursor, max, tx);
```
Comment (rustyrussell) [inline wire/fromwire.c]: You didn't mention in the commit msg that this was also a cleanup to use the new pull_bitcoin_tx_onto, though reading as a series that was unsurprising :)

File: contrib/pylightning/setup.py [hunk 4]
```diff
@@ -1,7 +1,7 @@
 from setuptools import setup
 
 setup(name='pylightning',
-      version='0.0.1',
+      version='0.0.2',
```
Comment (rustyrussell) [inline contrib/pylightning/setup.py]: This change seems unrelated?

Comment (cdecker) [reply contrib/pylightning/setup.py]: It is yes, I'll split it out and batch it with some other pylightning changes.

File: common/permute_tx.c (hunk 2 above)
Comment (cdecker) [reply common/permute_tx.c]: Fixed the `num_inputs` case I missed. The sanity check in `swap_inputs` and `swap_outputs` however is necessary, since `find_best_out` and `find_best_in` return a 0 offset if no better input/output is found, i.e., if the element is already at the correct location, which would then result in the overlap again.

File: wire/fromwire.c (hunk 3 above)
Comment (cdecker) [reply wire/fromwire.c]: Commit message now mentions this, good catch.

**Comment by cdecker** [comment]
Addressed review, fixed in-place and rebased on top of `master`. Merging as suggested by @rustyrussell
