### PR TITLE
Various minor fixes

### LINKED ISSUE #4434: Is `invoice_payment` notification called before the `invoice_payment` hook?
I didn't try this, just reading the code:

https://github.com/ElementsProject/lightning/blob/b563cafd838fd4e49fcea335f4d5af491997c3ca/lightningd/invoice.c#L420-L437

So we may get `invoice_payment` but then a hook goes there and fails the payment, so the notification was a lie?

### LINKED ISSUE #4438: Plugin keysend crashes lightning node when a node is trying to keysend to itself by mistake
If your lightning node id is ID then `lightning-cli keysend ID amount` will crash the node. Not that I made that mistake of course :-)

```
keysend: FATAL SIGNAL 6 (version v0.9.3-279-g2586641)
0x563581a01a73 send_backtrace
        common/daemon.c:39
0x563581a01b06 crashdump
        common/daemon.c:52
0x7fdc23bf003f ???
        ???:0
0x7fdc23beffb7 ???
        ???:0
0x7fdc23bf1920 ???
        ???:0
0x5635819f20d9 payment_route_fee
        plugins/libplugin-pay.c:430
0x5635819f3ce8 payment_getroute
        plugins/libplugin-pay.c:817
0x5635819f405d payment_continue
        plugins/libplugin-pay.c:2012
0x5635819f5ca1 retry_step_cb
        plugins/libplugin-pay.c:2180
0x5635819f402f payment_continue
        plugins/libplugin-pay.c:2004
0x5635819f4c98 waitblockheight_cb
        plugins/libplugin-pay.c:3252
0x5635819f402f payment_continue
        plugins/libplugin-pay.c:2004
0x5635819f4ae2 exemptfee_cb
        plugins/libplugin-pay.c:2859
0x5635819f402f payment_continue
        plugins/libplugin-pay.c:2004
0x5635819f6553 shadow_route_listchannels
        plugins/libplugin-pay.c:3056
0x5635819eebb9 handle_rpc_reply
        plugins/libplugin.c:564
0x5635819eecab rpc_read_response_one
        plugins/libplugin.c:711
0x5635819eed60 rpc_conn_read_response
        plugins/libplugin.c:731
0x563581a1054f next_plan
        ccan/ccan/io/io.c:59
0x563581a10a3e do_plan
        ccan/ccan/io/io.c:407
0x563581a10a6b io_ready
        ccan/ccan/io/io.c:417
0x563581a12337 io_loop
        ccan/ccan/io/poll.c:445
0x5635819ef890 plugin_main
        plugins/libplugin.c:1414
0x5635819ec3b5 main
        plugins/keysend.c:383
0x7fdc23bd2bf6 ???
        ???:0
0x5635819e8749 ???
        ???:0
0xffffffffffffffff ???
        ???:0
keysend: FATAL SIGNAL 11 (version v0.9.3-279-g2586641)
0x563581a01a73 send_backtrace
        common/daemon.c:39
0x563581a01b06 crashdump
        common/daemon.c:52
0x7fdc23bf003f ???
        ???:0
0x0 ???
        ???:0
2021-03-16T14:45:26.480Z INFO    plugin-keysend: Killing plugin: exited during normal operation
2021-03-16T14:45:26.480Z **BROKEN** plugin-keysend: Plugin marked as important, shutting down lightningd!
```

### PR DESCRIPTION
**Pull request by cdecker**
All of these are just single-commit fixes, so I didn't open a new PR for each:

 - We were stealing the plugin's read buffer in keysend and freeing it, causing a use-after-free on the next call.
 - Self-payments in `keysend` could result in a crash due to an empty route being returned.
 - The order in which the `invoice_payment` hook and notification were called was switched around (we were notifying about still to accept invoices being paid, when the hook could also reject it)

Fixes #4438 
Fixes #4434

### CODE REVIEW

File: plugins/keysend.c [hunk 1]
```diff
@@ -171,13 +171,19 @@ static struct command_result *json_keysend(struct command *cmd, const char *buf,
...
 
+	if (node_id_eq(&my_id, p->destination)) {
+		return command_fail(
+		    cmd, JSONRPC2_INVALID_PARAMS,
+		    "We are the destination. Keysend cannot be used to send funds to yourself");
+	}
+
 	if (!amount_msat_fee(&p->constraints.fee_budget, p->amount, 0,
 			     *maxfee_pct_millionths / 100)) {
-		tal_free(p);
```
Comment (cdecker) [inline plugins/keysend.c:176]: Notice that this is allocated off of `cmd`, which we free at the end of the JSON-RPC call anyway. So no need to free it early

**Review by rustyrussell — APPROVED** [review]
Ack 745e9325e99169253ff3e49f59ad8764bcf1a280

**Comment by rustyrussell** [comment]
Lots of random timeouts on CI.  I've disabled EXPERIMENTAL testing for the moment,  hoping to get a clean run for merge for rc1.

File: plugins/keysend.c [hunk 2]
```diff
@@ -171,13 +171,19 @@ static struct command_result *json_keysend(struct command *cmd, const char *buf,
...
 		return command_fail(
 		    cmd, JSONRPC2_INVALID_PARAMS,
 		    "Overflow when computing fee budget, fee rate too high.");
 	}
+
```
Comment (niftynei) [inline plugins/keysend.c:186]: nit: extraneous line change?
