### PR TITLE
Fix the multi-part payments

### LINKED ISSUE #3553: Remove the UNUSUAL warning about plugin bcli
The first c-lightning output a user sees is the following message:

`UNUSUAL plugin-bcli: Could not connect to 'lightning-rpc': Connection refused`

as kindly explained by **darosior**

_It's the expected behavior: a new plugin (bcli) introduced in the last release needs to be initialized before we even start listening on the RPC socket, hence it fails the connect()._

If it's expected behavior, c-lightning shouldn't output UNUSUAL. It got me on the wrong track when updating to version 0.8.1. This should be corrected in some way.

### LINKED ISSUE #3851: Failure to update constraints in shadow route modifier
```
pay: plugins/libplugin-pay.c:1850: shadow_route_listchannels: Assertion `ok' failed.
pay: FATAL SIGNAL 6 (version v0.9.0rc1-11-gc984376)
0x417e3e send_backtrace
        common/daemon.c:38
0x417ec8 crashdump
        common/daemon.c:51
0x7fba46a534af ???
        ???:0
0x7fba46a53428 ???
        ???:0
0x7fba46a55029 ???
        ???:0
0x7fba46a4bbd6 ???
        ???:0
0x7fba46a4bc81 ???
        ???:0
0x40e7c3 shadow_route_listchannels
        plugins/libplugin-pay.c:1850
0x4091de handle_rpc_reply
        plugins/libplugin.c:547
0x4092b3 rpc_read_response_one
        plugins/libplugin.c:662
0x40933b rpc_conn_read_response
        plugins/libplugin.c:681
0x426ced next_plan
        ccan/ccan/io/io.c:59
0x4271ad do_plan
        ccan/ccan/io/io.c:407
0x4271d8 io_ready
        ccan/ccan/io/io.c:417
0x428973 io_loop
        ccan/ccan/io/poll.c:445
0x409d96 plugin_main
        plugins/libplugin.c:1284
0x407086 main
        plugins/pay.c:2010
0x7fba46a3e82f ???
        ???:0
0x402e08 ???
        ???:0
0xffffffffffffffff ???
        ???:0
pay: FATAL SIGNAL 11 (version v0.9.0rc1-11-gc984376)
0x417e3e send_backtrace
        common/daemon.c:38
0x417ec8 crashdump
        common/daemon.c:51
0x7fba46a534af ???
        ???:0
0x0 ???
        ???:0
```

### LINKED ISSUE #3852: pay fails with 0.9.0-rc2
### Issue and Steps to Reproduce

Spark payment of 25,000 sat.

```
2020-07-19T02:04:43.987Z DEBUG plugin-manager: started(2100) /home/rusty/lightning/lightningd/../plugins/pay
2020-07-19T02:04:44.943Z DEBUG plugin-manager: started(2106) /home/rusty/.lightning/plugins/listpayments.py
2020-07-19T02:59:27.600Z INFO plugin-pay: Split into 3 sub-payments due to initial size (25000000msat > 10000000msat)
2020-07-19T03:09:10.168Z INFO plugin-pay: Split into 3 sub-payments due to initial size (25000000msat > 10000000msat)
2020-07-19T03:09:10.314Z INFO plugin-pay: Split into 3 sub-payments due to initial size (25000000msat > 10000000msat)
2020-07-19T03:09:10.365Z INFO plugin-pay: Split into 3 sub-payments due to initial size (25000000msat > 10000000msat)
2020-07-19T03:09:10.479Z INFO plugin-pay: Split into 3 sub-payments due to initial size (25000000msat > 10000000msat)
2020-07-19T03:16:47.397Z UNUSUAL plugin-pay: Unable to parse `waitsendpay` result: {\"code\":209,\"message\":\"Payment failure reason unknown\"}
2020-07-19T03:16:47.403Z INFO plugin-pay: Payment deadline expired, not retrying (partial-)payment 0937cf5eb3ddce160b9b3f3325b15df096938f4dab68022059fe5bc5acee0d76/2
2020-07-19T03:25:20.604Z UNUSUAL plugin-pay: Unable to parse `waitsendpay` result: {\"code\":209,\"message\":\"Payment failure reason unknown\"}
2020-07-19T03:25:20.609Z INFO plugin-pay: Payment deadline expired, not retrying (partial-)payment 0937cf5eb3ddce160b9b3f3325b15df096938f4dab68022059fe5bc5acee0d76/1
2020-07-19T03:25:20.610Z UNUSUAL plugin-pay: Unable to parse `waitsendpay` result: {\"code\":209,\"message\":\"Payment failure reason unknown\"}
2020-07-19T03:25:20.615Z INFO plugin-pay: Payment deadline expired, not retrying (partial-)payment 0937cf5eb3ddce160b9b3f3325b15df096938f4dab68022059fe5bc5acee0d76/3
2020-07-19T03:25:23.897Z INFO plugin-pay: failed: WIRE_TEMPORARY_CHANNEL_FAILURE (reply from remote)
2020-07-19T03:25:23.898Z INFO plugin-pay: Payment deadline expired, not retrying (partial-)payment 0937cf5eb3ddce160b9b3f3325b15df096938f4dab68022059fe5bc5acee0d76/2
2020-07-19T03:25:23.940Z INFO plugin-pay: failed: WIRE_TEMPORARY_CHANNEL_FAILURE (reply from remote)
2020-07-19T03:25:23.942Z INFO plugin-pay: Payment deadline expired, not retrying (partial-)payment 0937cf5eb3ddce160b9b3f3325b15df096938f4dab68022059fe5bc5acee0d76/2
2020-07-19T03:25:23.955Z UNUSUAL plugin-pay: Unable to parse `waitsendpay` result: {\"code\":209,\"message\":\"Payment failure reason unknown\"}
2020-07-19T03:25:23.969Z INFO plugin-pay: Payment deadline expired, not retrying (partial-)payment 0937cf5eb3ddce160b9b3f3325b15df096938f4dab68022059fe5bc5acee0d76/2
2020-07-19T03:25:24.035Z UNUSUAL plugin-pay: Unable to parse `waitsendpay` result: {\"code\":209,\"message\":\"Payment failure reason unknown\"}
2020-07-19T03:25:24.060Z INFO plugin-pay: Payment deadline expired, not retrying (partial-)payment 0937cf5eb3ddce160b9b3f3325b15df096938f4dab68022059fe5bc5acee0d76/2
2020-07-19T03:25:29.874Z INFO plugin-pay: failed: WIRE_TEMPORARY_CHANNEL_FAILURE (reply from remote)
2020-07-19T03:25:29.961Z INFO plugin-pay: Payment deadline expired, not retrying (partial-)payment 0937cf5eb3ddce160b9b3f3325b15df096938f4dab68022059fe5bc5acee0d76/3
2020-07-19T03:25:29.962Z INFO plugin-pay: failed: WIRE_TEMPORARY_CHANNEL_FAILURE (reply from remote)
2020-07-19T03:25:29.964Z INFO plugin-pay: Payment deadline expired, not retrying (partial-)payment 0937cf5eb3ddce160b9b3f3325b15df096938f4dab68022059fe5bc5acee0d76/3
2020-07-19T03:25:29.971Z INFO plugin-pay: failed: WIRE_TEMPORARY_CHANNEL_FAILURE (reply from remote)
2020-07-19T03:25:29.972Z INFO plugin-pay: Payment deadline expired, not retrying (partial-)payment 0937cf5eb3ddce160b9b3f3325b15df096938f4dab68022059fe5bc5acee0d76/3
2020-07-19T03:25:29.973Z INFO plugin-pay: failed: WIRE_TEMPORARY_CHANNEL_FAILURE (reply from remote)
2020-07-19T03:25:29.974Z INFO plugin-pay: Payment deadline expired, not retrying (partial-)payment 0937cf5eb3ddce160b9b3f3325b15df096938f4dab68022059fe5bc5acee0d76/3
2020-07-19T03:25:46.070Z INFO plugin-pay: Killing plugin: Plugin exited before completing handshake.
```

Valgrind errors (just first two)
```
==2100== Conditional jump or move depends on uninitialised value(s)
==2100==    at 0x11BD4F: payment_finished (libplugin-pay.c:1105)
==2100==    by 0x11B884: payment_child_finished (libplugin-pay.c:1006)
==2100==    by 0x11C0B2: payment_finished (libplugin-pay.c:1183)
==2100==    by 0x11C20C: payment_continue (libplugin-pay.c:1230)
==2100==    by 0x11EE5F: adaptive_splitter_cb (libplugin-pay.c:2252)
==2100==    by 0x11C197: payment_continue (libplugin-pay.c:1210)
==2100==    by 0x11C6BF: retry_step_cb (libplugin-pay.c:1369)
==2100==    by 0x11C197: payment_continue (libplugin-pay.c:1210)
==2100==    by 0x11E69B: waitblockheight_cb (libplugin-pay.c:2031)
==2100==    by 0x11C197: payment_continue (libplugin-pay.c:1210)
==2100==    by 0x11D7C3: routehint_step_cb (libplugin-pay.c:1658)
==2100==    by 0x11C197: payment_continue (libplugin-pay.c:1210)
==2100== 
==2100== Conditional jump or move depends on uninitialised value(s)
==2100==    at 0x544E96A: vfprintf (vfprintf.c:1642)
==2100==    by 0x547A97F: vsnprintf (vsnprintf.c:114)
==2100==    by 0x155C99: do_vfmt (str.c:66)
==2100==    by 0x155D7F: tal_vfmt_ (str.c:92)
==2100==    by 0x155BE8: tal_fmt_ (str.c:44)
==2100==    by 0x11BD84: payment_finished (libplugin-pay.c:1105)
==2100==    by 0x11B884: payment_child_finished (libplugin-pay.c:1006)
==2100==    by 0x11C0B2: payment_finished (libplugin-pay.c:1183)
==2100==    by 0x11C20C: payment_continue (libplugin-pay.c:1230)
==2100==    by 0x11EE5F: adaptive_splitter_cb (libplugin-pay.c:2252)
==2100==    by 0x11C197: payment_continue (libplugin-pay.c:1210)
==2100==    by 0x11C6BF: retry_step_cb (libplugin-pay.c:1369)
```

Crash:
```
pay: plugins/libplugin-pay.c:702: payment_waitsendpay_finished: Assertion `*p->result->erring_index < tal_count(p->route)' failed.
pay: FATAL SIGNAL 6 (version v0.9.0rc2)
0x12e0cf send_backtrace
	common/daemon.c:38
0x12e175 crashdump
	common/daemon.c:51
0x5430fcf ???
	???:0
0x5430f47 ???
	???:0
0x54328b0 ???
	???:0
0x5422429 ???
	???:0
0x54224a1 ???
	???:0
0x11a970 payment_waitsendpay_finished
	plugins/libplugin-pay.c:702
0x114b2b handle_rpc_reply
	plugins/libplugin.c:539
0x115236 rpc_read_response_one
	plugins/libplugin.c:662
0x115327 rpc_conn_read_response
	plugins/libplugin.c:681
0x146a63 next_plan
	ccan/ccan/io/io.c:59
0x1475e0 do_plan
	ccan/ccan/io/io.c:407
0x14761e io_ready
	ccan/ccan/io/io.c:417
0x1497e4 io_loop
	ccan/ccan/io/poll.c:445
0x1174bb plugin_main
	plugins/libplugin.c:1284
0x113777 main
	plugins/pay.c:2010
0x5413b96 ???
	???:0
0x10cc69 ???
	???:0
0xffffffffffffffff ???
	???:0
```
### `getinfo` output
```
{
   "id": "024b9a1fa8e006f1e3937f65f66c408e6da8e1ca728ea43222a7381df1cc449605",
   "alias": "BLUEIRON-v0.9.0rc2",
   "color": "024b9a",
   "num_peers": 31,
   "num_pending_channels": 0,
   "num_active_channels": 31,
   "num_inactive_channels": 0,
   "address": [
      {
         "type": "ipv4",
         "address": "128.199.202.168",
         "port": 9735
      },
      {
         "type": "ipv6",
         "address": "2400:6180:0:d0::5cd2:a001",
         "port": 9735
      },
      {
         "type": "torv3",
         "address": "ki5uack5xb4gicfnpfavzdibojfu3qvwtlg3ca7eyjxik7tgwfxummqd.onion",
         "port": 9735
      },
      {
         "type": "torv3",
         "address": "3kwzm4b4qgzafj4fkicsdjpptkgtohojdby2tyybmlf44t5xug7kqrqd.onion",
         "port": 9735
      }
   ],
   "binding": [
      {
         "type": "ipv6",
         "address": "::",
         "port": 9735
      },
      {
         "type": "ipv4",
         "address": "0.0.0.0",
         "port": 9735
      }
   ],
   "version": "v0.9.0rc2",
   "blockheight": 639834,
   "network": "bitcoin",
   "msatoshi_fees_collected": 304561,
   "fees_collected_msat": "304561msat",
   "lightning-dir": "/home/rusty/.lightning/bitcoin"
```

### LINKED ISSUE #3855: Pay plugin stop to work after call "pay an_bolt11"
Hi all,

I'm testing the 0.9.0-rc2, in particular my configuration include one node with 0.9.0-rc2 on desktop and two node 0.8.2 on android. I'm testing the to open channels and pay bolt11 from different node but today I run the last rc version from the code and I receive the following error

```json
{
   "code": -4,
   "message": "Plugin terminated before replying to RPC call."
}
```

With the following stakstrace
```
2020-07-19T13:00:24.463Z DEBUG 036c78a7959a62640a5f1e871d00ae0a47bb97907fc64da220dc0841d1fadd5d0c-gossipd: Received channel_update for channel 1781122x121x0/1 now ACTIVE
pay: plugins/libplugin-pay.c:1431: local_channel_hints_listpeers: Assertion `spendsats != NULL && scid != NULL && dir != NULL' failed.
pay: FATAL SIGNAL 6 (version v0.9.0rc2-15-g660a743)
0x5644f5402999 send_backtrace
	common/daemon.c:38
0x5644f5402a3f crashdump
	common/daemon.c:51
0x7f7f0cb85fcf ???
	???:0
0x7f7f0cb85f47 ???
	???:0
0x7f7f0cb878b0 ???
	???:0
0x7f7f0cb77429 ???
	???:0
0x7f7f0cb774a1 ???
	???:0
0x5644f53f1299 local_channel_hints_listpeers
	plugins/libplugin-pay.c:1431
0x5644f53e94a6 handle_rpc_reply
	plugins/libplugin.c:547
0x5644f53e9b16 rpc_read_response_one
	plugins/libplugin.c:662
0x5644f53e9c07 rpc_conn_read_response
	plugins/libplugin.c:681
0x5644f5419e25 next_plan
	ccan/ccan/io/io.c:59
0x5644f541a9a2 do_plan
	ccan/ccan/io/io.c:407
0x5644f541a9e0 io_ready
	ccan/ccan/io/io.c:417
0x5644f541cba6 io_loop
	ccan/ccan/io/poll.c:445
0x5644f53ebd9b plugin_main
	plugins/libplugin.c:1284
0x5644f53e8057 main
	plugins/pay.c:2010
0x7f7f0cb68b96 ???
	???:0
0x5644f53e1549 ???
	???:0
0xffffffffffffffff ???
	???:0
pay: FATAL SIGNAL 11 (version v0.9.0rc2-15-g660a743)
0x5644f5402999 send_backtrace
	common/daemon.c:38
0x5644f5402a3f crashdump
	common/daemon.c:51
0x7f7f0cb85fcf ???
	???:0
0x0 ???
	???:0
2020-07-19T13:00:33.215Z INFO plugin-pay: Killing plugin: Plugin exited before completing handshake.

```

### Issue and Steps to Reproduce

I can describe my configuration with the testnet network.

Node A: rc2 version on linux
Node B: 0.8.2 on android
Node C: 0.8.2 on android

I open the channel with the following order

A->B->C

With C I generate the bol11 and I want to pay the bolt11 with the node A but after run command pay I received the error described in the previous section

When I try to pay the bolt11 from B to node C I receive the `could not find a route` error

The staus of the channel are

Node A with id: `0360dca2f35336d303643a7fb172ba6185b9086aa1fbd6063a1447050f2dda0f87`

`listchannels`

```json
{
   "channels": [
      {
         "source": "0360dca2f35336d303643a7fb172ba6185b9086aa1fbd6063a1447050f2dda0f87",
         "destination": "036c78a7959a62640a5f1e871d00ae0a47bb97907fc64da220dc0841d1fadd5d0c",
         "short_channel_id": "1781122x121x0",
         "public": false,
         "satoshis": 10000,
         "amount_msat": "10000000msat",
         "message_flags": 1,
         "channel_flags": 0,
         "active": true,
         "last_update": 1595163626,
         "base_fee_millisatoshi": 1,
         "fee_per_millionth": 10,
         "delay": 6,
         "htlc_minimum_msat": "0msat",
         "htlc_maximum_msat": "9454000msat",
         "features": ""
      },
      {
         "source": "036c78a7959a62640a5f1e871d00ae0a47bb97907fc64da220dc0841d1fadd5d0c",
         "destination": "0360dca2f35336d303643a7fb172ba6185b9086aa1fbd6063a1447050f2dda0f87",
         "short_channel_id": "1781122x121x0",
         "public": false,
         "satoshis": 10000,
         "amount_msat": "10000000msat",
         "message_flags": 1,
         "channel_flags": 1,
         "active": true,
         "last_update": 1595163624,
         "base_fee_millisatoshi": 1,
         "fee_per_millionth": 10,
         "delay": 6,
         "htlc_minimum_msat": "0msat",
         "htlc_maximum_msat": "9454000msat",
         "features": ""
      }
   ]
}
```

Node B with id `036c78a7959a62640a5f1e871d00ae0a47bb97907fc64da220dc0841d1fadd5d0c`

listchannels

```json
,$ lightning-cli listchannels
{
   "channels": [
      {
         "source": "0360dca2f35336d303643a7fb172ba6185b9086aa1fbd6063a1447050f2dda0f87",
         "destination": "036c78a7959a62640a5f1e871d00ae0a47bb97907fc64da220dc0841d1fadd5d0c",
         "short_channel_id": "1781122x121x0",
         "public": false,
         "satoshis": 10000,
         "amount_msat": "10000000msat",
         "message_flags": 1,
         "channel_flags": 0,
         "active": true,
         "last_update": 1595163626,
         "base_fee_millisatoshi": 1,
         "fee_per_millionth": 10,
         "delay": 6,
         "htlc_minimum_msat": "0msat",
         "htlc_maximum_msat": "9454000msat"
      },
      {
         "source": "036c78a7959a62640a5f1e871d00ae0a47bb97907fc64da220dc0841d1fadd5d0c",
         "destination": "0360dca2f35336d303643a7fb172ba6185b9086aa1fbd6063a1447050f2dda0f87",
         "short_channel_id": "1781122x121x0",
         "public": false,
         "satoshis": 10000,
         "amount_msat": "10000000msat",
         "message_flags": 1,
         "channel_flags": 1,
         "active": true,
         "last_update": 1595163624,
         "base_fee_millisatoshi": 1,
         "fee_per_millionth": 10,
         "delay": 6,
         "htlc_minimum_msat": "0msat",
         "htlc_maximum_msat": "9454000msat"
      },
      {
         "source": "02824defe8bf628f676f44a01e02a22c1c613571e1e55df738d6ad072310fb7bf8",
         "destination": "036c78a7959a62640a5f1e871d00ae0a47bb97907fc64da220dc0841d1fadd5d0c",
         "short_channel_id": "1781123x197x0",
         "public": false,
         "satoshis": 10000,
         "amount_msat": "10000000msat",
         "message_flags": 1,
         "channel_flags": 0,
         "active": false,
         "last_update": 1595163857,
         "base_fee_millisatoshi": 1,
         "fee_per_millionth": 10,
         "delay": 6,
         "htlc_minimum_msat": "0msat",
         "htlc_maximum_msat": "9454000msat"
      },
      {
         "source": "036c78a7959a62640a5f1e871d00ae0a47bb97907fc64da220dc0841d1fadd5d0c",
         "destination": "02824defe8bf628f676f44a01e02a22c1c613571e1e55df738d6ad072310fb7bf8",
         "short_channel_id": "1781123x197x0",
         "public": false,
         "satoshis": 10000,
         "amount_msat": "10000000msat",
         "message_flags": 1,
         "channel_flags": 1,
         "active": false,
         "last_update": 1595163855,
         "base_fee_millisatoshi": 1,
         "fee_per_millionth": 10,
         "delay": 6,
         "htlc_minimum_msat": "0msat",
         "htlc_maximum_msat": "9454000msat"
      }
   ]
}
```

Node C with id `02824defe8bf628f676f44a01e02a22c1c613571e1e55df738d6ad072310fb7bf8`

listchannels

```json
$ lightning-cli listchannels
{ 
   "channels": [ 
      { 
         "source": "02824defe8bf628f676f44a01e02a22c1c613571e1e55df738d6ad072310fb7bf8", 
         "destination": "036c78a7959a62640a5f1e871d00ae0a47bb97907fc64da220dc0841d1fadd5d0c", 
         "short_channel_id": "1781123x197x0", 
         "public": false, 
         "satoshis": 10000, 
         "amount_msat": "10000000msat", 
         "message_flags": 1, 
         "channel_flags": 0, 
         "active": true, 
         "last_update": 1595165728, 
         "base_fee_millisatoshi": 1, 
         "fee_per_millionth": 10, 
         "delay": 6, 
         "htlc_minimum_msat": "0msat", 
         "htlc_maximum_msat": "9454000msat" 
      }, 
      { 
         "source": "036c78a7959a62640a5f1e871d00ae0a47bb97907fc64da220dc0841d1fadd5d0c", 
         "destination": "02824defe8bf628f676f44a01e02a22c1c613571e1e55df738d6ad072310fb7bf8", 
         "short_channel_id": "1781123x197x0", 
         "public": false, 
         "satoshis": 10000, 
         "amount_msat": "10000000msat", 
         "message_flags": 1, 
         "channel_flags": 1, 
         "active": true, 
         "last_update": 1595165726, 
         "base_fee_millisatoshi": 1, 
         "fee_per_millionth": 10, 
         "delay": 6, 
         "htlc_minimum_msat": "0msat", 
         "htlc_maximum_msat": "9454000msat" 
      } 
   ] 
}
```

### `getinfo` output

```json
{   "id": "0360dca2f35336d303643a7fb172ba6185b9086aa1fbd6063a1447050f2dda0f87",
   "alias": "BRUCEWAYN-TES-DEV",
   "color": "03ad98",
   "num_peers": 2,
   "num_pending_channels": 0,
   "num_active_channels": 1,
   "num_inactive_channels": 3,
   "address": [
      {
         "type": "torv3",
         "address": "fp463inc4w3lamhhduytrwdwq6q6uzugtaeapylqfc43agrdnnqsheyd.onion",
         "port": 9735
      },
      {
         "type": "torv3",
         "address": "3xjyamprb43ubatvfr3ruvpj2bdolkko6jrcbevwjb2o37o7reacjvad.onion",
         "port": 9735
      }
   ],
   "binding": [
      {
         "type": "ipv4",
         "address": "127.0.0.1",
         "port": 9735
      }
   ],
   "version": "v0.9.0rc2-15-g660a743",
   "blockheight": 1781124,
   "network": "testnet",
   "msatoshi_fees_collected": 0,
   "fees_collected_msat": "0msat",
   "lightning-dir": "/media/vincent/Maxtor/sanboxTestWrapperRPC/lightning_dir_dev/testnet"
}
```

The behavior that I aspect from the rc2 should be the same from the 0.8.2 version? in other words, the paid plugin should return the error `could not find a route`. I'm losing somethings and this behavior is correct and my mind contains a bug?

### LINKED ISSUE #3859: After system reboot >> Could not connect to 'lightning-rpc': Connection refused
### Issue

I have read everything there is to read about this error but, the only answer i've found is that `lightningd` isn't running. Well, that isn't the case with here.

#### System

OS: Debian/buster64
ENV: Vagrant
bitcoind dir: ~/.bitcnoind
lightningd dir: ~/.lightnind

#### Steps to reproduce:

1. Fresh install `bitcoind`
2. Install `lightningd`
3. Run rpc commands - all good.
4. Reboot system
5. Get the error

Following is the output of `lightnind` after reboot:

```sh
2020-07-20T02:59:44.639Z UNUSUAL plugin-bcli: Could not connect to 'lightning-rpc': Connection refused
2020-07-20T02:59:44.652Z INFO plugin-bcli: bitcoin-cli initialized and connected to bitcoind.
2020-07-20T02:59:44.730Z UNUSUAL lightningd: Waiting for initial block download (this can take a while!)
2020-07-20T02:59:44.732Z UNUSUAL lightningd: Unable to estimate opening fees
...
2020-07-20T02:59:44.732Z UNUSUAL lightningd: Unable to estimate max_acceptable fees
2020-07-20T02:59:44.925Z UNUSUAL plugin-bcli: bitcoin-cli getblock 00000000000000ad6082acfe902b2ee294f4d1219f12b67bf59f88bb9d4af729 0 exited with status 1
```

Is this a case of file permissions? Directory paths? ..? I have no clue what i'm doing wrong. I've followed the install process to the T.

Any help highly appreciated.

### `getinfo` output

`Could not connect to 'lightning-rpc': Connection refused`

### PR DESCRIPTION
**Pull request by cdecker**
Fixes #3852
Fixes #3851 
Fixes #3855

Removes the scary warning about `bcli` not being able to auto-connect to the JSON-RPC:
Fixes #3553
Fixes #3859

### CODE REVIEW

File: lightningd/pay.c [hunk 1]
```diff
@@ -793,14 +793,6 @@ send_payment_core(struct lightningd *ld,
 	/* Now, do we already have one or more payments? */
 	payments = wallet_payment_list(tmpctx, ld->wallet, rhash);
 	for (size_t i = 0; i < tal_count(payments); i++) {
-		log_debug(ld->log, "Payment %zu/%zu: %s %s",
```
Comment (ZmnSCPxj) [inline lightningd/pay.c:796]: Could instead put payment parts into bins of COMPLETE/PENDING/FAILED, then print something like "249 payments: COMPLETE 0 0msat, PENDING: 60 60msat, FAILED: 189 189msat"

File: plugins/libplugin-pay.c [hunk 2]
```diff
@@ -1750,13 +1750,9 @@ REGISTER_PAYMENT_MODIFIER(exemptfee, struct exemptfee_data *,
...
 static struct shadow_route_data *shadow_route_init(struct payment *p)
 {
-	if (p->parent != NULL) {
-		return payment_mod_shadowroute_get_data(p->parent);
-	} else {
-		struct shadow_route_data *d = tal(p, struct shadow_route_data);
-		d->fuzz_amount = true;
-		return d;
-	}
+	struct shadow_route_data *d = tal(p, struct shadow_route_data);
```
Comment (ZmnSCPxj) [inline plugins/libplugin-pay.c]: +1

File: plugins/libplugin-pay.c [hunk 3]
```diff
@@ -660,129 +661,298 @@ static void payment_result_infer(struct route_hop *route,
...
+	case WIRE_PERMANENT_CHANNEL_FAILURE:
+	case WIRE_REQUIRED_CHANNEL_FEATURE_MISSING:
+	case WIRE_UNKNOWN_NEXT_PEER:
+	case WIRE_AMOUNT_BELOW_MINIMUM:
+	case WIRE_FEE_INSUFFICIENT:
+	case WIRE_INCORRECT_CLTV_EXPIRY:
+	case WIRE_EXPIRY_TOO_FAR:
+	case WIRE_EXPIRY_TOO_SOON:
+	case WIRE_CHANNEL_DISABLED:
+		goto strange_error;
```
Comment (ZmnSCPxj) [inline plugins/libplugin-pay.c:749]: Since this failure code is from remote, the remote might suddenly give us some unknown failure code.  Of course, that means we just fall-through into `strange_error`, which is appropriate.

File: plugins/libplugin-pay.c [hunk 4]
```diff
@@ -660,129 +661,298 @@ static void payment_result_infer(struct route_hop *route,
...
+
+	case WIRE_INVALID_ONION_PAYLOAD:
+	case WIRE_INVALID_REALM:
+	case WIRE_PERMANENT_NODE_FAILURE:
+	case WIRE_TEMPORARY_NODE_FAILURE:
+	case WIRE_REQUIRED_NODE_FEATURE_MISSING:
+#if EXPERIMENTAL_FEATURES
+	case WIRE_INVALID_ONION_BLINDING:
+#endif
+ 	case WIRE_INCORRECT_OR_UNKNOWN_PAYMENT_DETAILS:
```
Comment (ZmnSCPxj) [inline plugins/libplugin-pay.c:759]: No special handling for this a la #3376?  Or is this maybe handled elsewhere?

Comment (cdecker) [reply plugins/libplugin-pay.c:759]: That is indeed handled in the `waitblockheight` modifier which encapsulates all the specialties around that failure.

**Comment by cdecker** [comment]
Cherry-picked the contents of #3856 as suggested by @ZmnSCPxj but maintained authorship, since credit goes to @vincenzopalazzo and @ZmnSCPxj for finding this and fixing it before I could even look at it :+1:

File: plugins/libplugin-pay.c (hunk 4 above)
Comment (ZmnSCPxj) [reply plugins/libplugin-pay.c:759]: ah okthx, nice.

File: lightningd/pay.c (hunk 1 above)
Comment (cdecker) [reply lightningd/pay.c]: Removed this change for now, since it broke at least one test :-)
Will reconsider removing it again later.

**Comment by cdecker** [comment]
Rebased and squashed after merding #3860

**Comment by rustyrussell** [comment]
OK, this passed the Twitter test!

Minor issue, it splits 2x too aggressively, proposed fix here:
https://github.com/rustyrussell/lightning/commit/49cb5ba9e2b235cd80b2248e3113d82ac9e30809

**Comment by rustyrussell** [comment]
Ack https://github.com/ElementsProject/lightning/pull/3857/commits/d6bb19138e73134dd60637b790b42fef4e0edb22

**Comment by ZmnSCPxj** [comment]
Perhaps late to bring this up, but: do we need to actually arrange payments in a *tree* as opposed to a flat array of sub-payments?

The reason I bring this up is because we might want to *merge* sub-payments.  For example, consider the case where the only viable paths for two sub-payments cost too much (i.e. fee budget is violated), but if we merge them (and their fee budgets) we could succeed.

But if the sub-payments we want to merge are cousins instead of siblings in the tree of payments, how do we viably merge them?  For example, consider the case below:

            0
           / \
          /   \
         1     2
        / \   / \
       3   4 5   6

Suppose 4 and 6 are currently ongoing (possibly because they reached the destination, so the destination is waiting on the other parts).  And 3 and 5 are failing `getroute` because the viable routes are too expensive.  However, if we merge 3 and 5, it may be feasible (because they would pool their fee budgets together).

As each subpayment needs a unique numeric id, we could use a monotonically-increasing counter and add an explicit field.  Merged payments can get any of the ids of the merged payments.

And of course modules have to handle merges as well, if their data structures are not `void`.

**Comment by rustyrussell** [comment]
Trivial rebase for typo fix.

**Comment by cdecker** [comment]
> Perhaps late to bring this up, but: do we need to actually arrange payments in a _tree_ as opposed to a flat array of sub-payments?
> 
> The reason I bring this up is because we might want to _merge_ sub-payments. For example, consider the case where the only viable paths for two sub-payments cost too much (i.e. fee budget is violated), but if we merge them (and their fee budgets) we could succeed.
> 
> But if the sub-payments we want to merge are cousins instead of siblings in the tree of payments, how do we viably merge them? For example, consider the case below:
> 
> ```
>         0
>        / \
>       /   \
>      1     2
>     / \   / \
>    3   4 5   6
> ```
> 
> Suppose 4 and 6 are currently ongoing (possibly because they reached the destination, so the destination is waiting on the other parts). And 3 and 5 are failing `getroute` because the viable routes are too expensive (e.g. 4 and 6 have locked up funds on cheaper routes). However, if we merge 3 and 5, it may be feasible (because they would pool their fee budgets together).
> 
> As each subpayment needs a unique numeric id, we could use a monotonically-increasing counter and add an explicit field. Merged payments can get any of the ids of the merged payments.
> 
> And of course modules have to handle merges as well, if their data structures are not `void`.



> Perhaps late to bring this up, but: do we need to actually arrange payments in a _tree_ as opposed to a flat array of sub-payments?
> 
> The reason I bring this up is because we might want to _merge_ sub-payments. For example, consider the case where the only viable paths for two sub-payments cost too much (i.e. fee budget is violated), but if we merge them (and their fee budgets) we could succeed.
> 
> But if the sub-payments we want to merge are cousins instead of siblings in the tree of payments, how do we viably merge them? For example, consider the case below:
> 
> ```
>         0
>        / \
>       /   \
>      1     2
>     / \   / \
>    3   4 5   6
> ```
> 
> Suppose 4 and 6 are currently ongoing (possibly because they reached the destination, so the destination is waiting on the other parts). And 3 and 5 are failing `getroute` because the viable routes are too expensive (e.g. 4 and 6 have locked up funds on cheaper routes). However, if we merge 3 and 5, it may be feasible (because they would pool their fee budgets together).
> 
> As each subpayment needs a unique numeric id, we could use a monotonically-increasing counter and add an explicit field. Merged payments can get any of the ids of the merged payments.
> 
> And of course modules have to handle merges as well, if their data structures are not `void`.

Discussions are always welcome, though I don't think that this should be discussed in a PR where it is likely to get lost, so I opened a [new issue](https://github.com/ElementsProject/lightning/issues/3863) for this.

The TL;DR is that I think the merging or not of payments is independent of how we link the payments internally. We can represent the tree in an array just as well, and as you point out the `partid` are consecutive already, so we could just also stash them in an additional array.

I'm wondering whether we'd want to merge at all, or whether other techniques such as fee stealing from other subpayments that we consider to "have worked" (TM) are more promising.
