### PR TITLE
That time Pieter Wuille tested us all and we failed him

### LINKED ISSUE #2063: UPPERCASE INVOICES FAIL
### Problem

Blockstream's store uses UPPERCASE invoices (they also prepend LIGHTNING:), giving '"Invoices must start with ln"'

This broke with 0.6.2's extra "must start with ln" check :(

### `getinfo` output
{
 "id": "024b9a1fa8e006f1e3937f65f66c408e6da8e1ca728ea43222a7381df1cc449605", 
  "alias": "BLUEIRON-v0.6.2rc1", 
  "color": "024b9a", 
  "address": [
    {
      "type": "ipv4", 
      "address": "128.199.202.168", 
      "port": 9735
    }, 
    {
      "type": "ipv6", 
      "address": "2400:6180:0:d0::5cd2:a001", 
      "port": 9735
    }, 
    {
      "type": "torv2", 
      "address": "m7uhnmknr5ell2jt.onion", 
      "port": 9735
    }
  ], 
  "binding": [
    {
      "type": "ipv6", 
      "address": "::", 
      "port": 9735
    }, 
    {
      "type": "ipv4", 
      "address": "0.0.0.0", 
      "port": 9735
    }
  ], 
  "version": "v0.6.2rc1", 
  "blockheight": 548063, 
  "network": "bitcoin", 
  "msatoshi_fees_collected": 0
}

### PR DESCRIPTION
**Pull request by rustyrussell**
Fixes #2063 as a side-effect.

### CODE REVIEW

File: common/bolt11.c [hunk 1]
```diff
@@ -467,11 +467,11 @@ struct bolt11 *bolt11_decode(const tal_t *ctx, const char *str,
...
         b11->routes = tal_arr(b11, struct route_info *, 0);
 
-        if (!strstarts(str, "ln"))
-                return decode_fail(b11, fail, "Invoices must start with ln");
+        if (strlen(str) < 8)
+                return decode_fail(b11, fail, "Bad bech32 string");
 
-        hrp = tal_arr(tmpctx, char, strlen(str));
-        data = tal_arr(tmpctx, u5, strlen(str));
+        hrp = tal_arr(tmpctx, char, strlen(str) - 6);
```
Comment (niftynei) [inline common/bolt11.c]: i realize this is a revert, so maybe this is already taken care of, but if not can you add some context about why these offsets are necessary, maybe as a code comment?

**Comment by cdecker** [comment]
ACK https://github.com/ElementsProject/lightning/pull/2061/commits/7e73ea7c3e9e1e4d3768594b2587ce8c536b3608

File: common/bolt11.c (hunk 1 above)
Comment (rustyrussell) [reply common/bolt11.c]: It's actually documented in the bech32 reference code header to have these requirements.

The reason: bech32 includes a 30-bit (6char) checksum, and a `1` between hrp and data, meaning hrp must be 7 chars shorter.  Plus one for NUL terminator, so -6.

The `data` is not NUL-terminated, *and* the code insists that hrp be at least one letter long, so that's -8.

But you made me re-read the code and write some test cases to be *sure*!
