### PR TITLE
Fix log injection attack and return on JSON parse failure

### LINKED ISSUE #908: RPC API should return error message when failing to parse JSON
Currently, when sending a RPC request with unescaped chars like in #387, lightningd returns an empty string when it should instead return a valid JSON RPC response like: 

```json
{
  "id": null,
  "error": {
    "code": -32700,
    "message": "Parse error"
  }
}
```

### LINKED ISSUE #945: Log injection possible via incorrect RPC calls
### Issue and Steps to Reproduce

In terminal 1:

```
$ lightningd/lightningd
2018-02-07T14:22:25.698Z lightningd(13329): Server started with public key …, alias … (color #…) and lightningd v0.5.2-…
```

In terminal 2:

```
$ cli/lightning-cli foo "$(clear; echo "I've now taken over your log. Sorry about that."; \
      echo " "; echo " ")"
lightning-cli: reading response: Success
```

Back in terminal 1:

```
[screen cleared]
I've now taken over your log. Sorry about that.

 "] }'
```

### PR DESCRIPTION
**Pull request by cdecker**
As reported by @practicalswift in #945 it is possible to inject
non-printable, or shell escape, characters in a json command, that
will fail to parse and then clear the shell.

The second commit also adds an error response when we're unable
to parse the request, just to be extra nice :wink: 

Fixes #945 
Fixes #908

### CODE REVIEW

**Comment by cdecker** [comment]
Fixes #945

**Comment by cdecker** [comment]
I guess if we indeed have a shell escape character in a string, e.g., invoice description, that'll trigger an invalid token error? In that case, I'll move the check to `logv` and `logv_add`.

**Comment by cdecker** [comment]
Removed check for unprintable characters in JSON, replaced with string sanitization in `logv` and `logv_add`. Please re-review @rustyrussell

File: lightningd/log.c [hunk 1]
```diff
@@ -289,6 +295,12 @@ void logv_add(struct log *log, const char *fmt, va_list ap)
 	list_del_from(&log->lr->log, &l->list);
 
 	tal_append_vfmt(&l->log, fmt, ap);
+
+	/* Sanitize any non-printable characters, and replace with '?' */
+	for (size_t i=0; i<strlen(l->log); i++)
```
Comment (rustyrussell) [inline lightningd/log.c]: You can iterate from oldlen, not 0, BTW, since this is a simple append...

File: lightningd/log.c [hunk 2]
```diff
@@ -289,6 +295,12 @@ void logv_add(struct log *log, const char *fmt, va_list ap)
...
+		if (l->log[i] < ' ' || l->log[i] >= 0x7f)
```
Comment (rustyrussell) [inline lightningd/log.c]: Should we be checking == 0x7f so we let through UTF-8?  That would seem sensible...

Comment (cdecker) [reply lightningd/log.c]: As much as I'd like to have UTF-8 support in here, that'd mean we now need to carry context and have multi-char replacements in some cases, e.g., there are multi-byte control characters again. I'm afraid that we probably won't get away without fully parsing UTF-8 at some point, so I'd prefer keeping this ASCII only for now, and have an issue open to support full UTF-8 with corresponding escaping.

**Comment by cdecker** [comment]
Rebased and started sanitization from `oldlen` as suggested by @rustyrussell 

ACK 5267456

**Comment by practicalswift** [comment]
Post-merge ACK 5267456d22e6e12b9924a81c75cfbfc1912c30a3

Sorry for the late review :-)
